/**
 * dashboard-logger.ts — Structured JSONL for examples/dashboard HTTP requests.
 *
 * Operator-surface audit trail (probe server, artifact routes, card health).
 * Replaces reliance on raw stderr in examples-dashboard.log for request telemetry.
 */

import { appendNdjsonRecordSync } from "./ndjson.ts";
import { examplesDashboardEventsPath } from "./paths.ts";

export const DASHBOARD_HTTP_LOG_SCHEMA_VERSION = 1 as const;

/** Loopback card probes set this header (see probeAllRegistryRoutes). */
export const DASHBOARD_PROBE_HEADER = "x-kimi-dashboard-probe";

export type DashboardLogLevel = "info" | "warn" | "error";

export interface DashboardLogEntry {
  schemaVersion: typeof DASHBOARD_HTTP_LOG_SCHEMA_VERSION;
  ts: number;
  level: DashboardLogLevel;
  route: string;
  method: string;
  status: number;
  durationMs: number;
  error?: string;
  /** True for /api/cards?probe= or X-Kimi-Dashboard-Probe loopback GETs. */
  probe?: boolean;
}

let _logPath: string | null = null;

function resolveLogPath(): string {
  if (!_logPath) _logPath = examplesDashboardEventsPath();
  return _logPath;
}

/** Test-only: override JSONL destination. */
export function setDashboardLogPath(path: string): void {
  _logPath = path;
}

export function resetDashboardLogPath(): void {
  _logPath = null;
}

export function levelForStatus(status: number): DashboardLogLevel {
  if (status >= 500) return "error";
  if (status >= 400) return "warn";
  return "info";
}

/** Whether this request was generated by the card probe fan-out. */
export function isDashboardProbeRequest(req: Request, url: URL): boolean {
  if (url.searchParams.get("probe") === "true") return true;
  return req.headers.get(DASHBOARD_PROBE_HEADER) === "1";
}

export function buildDashboardLogEntry(
  input: Omit<DashboardLogEntry, "schemaVersion"> & { schemaVersion?: number }
): DashboardLogEntry {
  return {
    ...input,
    schemaVersion: DASHBOARD_HTTP_LOG_SCHEMA_VERSION,
  };
}

/** Append one structured HTTP event line (best-effort; never throws). */
export function logDashboardEvent(entry: DashboardLogEntry): void {
  try {
    appendNdjsonRecordSync(resolveLogPath(), entry);
  } catch {
    // audit must not break the request path
  }
}
