/**
 * Shell completion scripts generated from discover CLI option specs.
 */

import {
  DISCOVER_CLI_META_SPECS,
  type DiscoverCliOptionSpec,
  type DiscoverShell,
} from "./discover-cli-specs.ts";

export type { DiscoverCompleteValuesKind, DiscoverShell } from "./discover-cli-specs.ts";

function primaryLongFlag(spec: DiscoverCliOptionSpec): string {
  return spec.flags.find((flag) => flag.startsWith("--")) ?? spec.flags[0]!;
}

function booleanFlagWords(specs: readonly DiscoverCliOptionSpec[]): string {
  return specs
    .filter((spec) => spec.kind === "boolean")
    .map((spec) => primaryLongFlag(spec))
    .join(" ");
}

function valueFlagWords(specs: readonly DiscoverCliOptionSpec[]): string {
  return specs
    .filter((spec) => spec.kind === "value")
    .map((spec) => primaryLongFlag(spec))
    .join(" ");
}

function allOptionWords(specs: readonly DiscoverCliOptionSpec[]): string {
  const boolean = booleanFlagWords(specs);
  const value = valueFlagWords(specs);
  const meta = DISCOVER_CLI_META_SPECS.map((spec) => spec.flags[0]).join(" ");
  return `${boolean} ${value} -h --help ${meta}`.replace(/\s+/g, " ").trim();
}

function installHeader(shell: DiscoverShell, discoverCmd: string): string[] {
  const path =
    shell === "bash" ? "~/.bun/completions/discover.bash" : "~/.zsh/completions/_discover";
  const enable =
    shell === "bash"
      ? "source ~/.bun/completions/discover.bash"
      : "fpath=(~/.zsh/completions $fpath); autoload -Uz compinit && compinit";

  return [
    `# Generated by: ${discoverCmd} --completion ${shell}`,
    `# Install: ${discoverCmd} --completion ${shell} > ${path}`,
    `# Enable: ${enable}`,
    `# Override invoke command: export DISCOVER_CMD='${discoverCmd}'`,
    "",
  ];
}

export function formatDiscoverBashCompletion(
  specs: readonly DiscoverCliOptionSpec[],
  discoverCmd = "bun run discover"
): string {
  const opts = allOptionWords(specs);
  const lines = [
    ...installHeader("bash", discoverCmd),
    "__discover_invoke() {",
    `  if [[ -n "\${DISCOVER_CMD:-}" ]]; then`,
    "    # shellcheck disable=SC2086",
    '    ${DISCOVER_CMD} "$@"',
    "  else",
    `    ${discoverCmd} "$@"`,
    "  fi",
    "}",
    "",
    "_discover() {",
    "  local cur prev",
    "  COMPREPLY=()",
    '  cur="${COMP_WORDS[COMP_CWORD]}"',
    '  prev="${COMP_WORDS[COMP_CWORD-1]}"',
    "",
    '  if [[ "${COMP_WORDS[0]}" == "discover" ]]; then',
    "    :",
    '  elif [[ "${COMP_WORDS[0]}" == "bun" && "${COMP_WORDS[1]}" == "run" && "${COMP_WORDS[2]}" == "discover" ]]; then',
    "    :",
    "  else",
    "    return",
    "  fi",
    "",
    `  local opts="${opts}"`,
    "",
    '  case "${prev}" in',
    "    --completion)",
    '      COMPREPLY=( $(compgen -W "bash zsh" -- "${cur}") )',
    "      return",
    "      ;;",
    "    --complete-values)",
    '      COMPREPLY=( $(compgen -W "domain key" -- "${cur}") )',
    "      return",
    "      ;;",
    "    --domain)",
    "      local domains",
    '      domains="$(__discover_invoke --complete-values domain --root "${PWD}" 2>/dev/null)"',
    '      COMPREPLY=( $(compgen -W "${domains}" -- "${cur}") )',
    "      return",
    "      ;;",
    "    --key)",
    "      local keys",
    '      keys="$(__discover_invoke --complete-values key --root "${PWD}" 2>/dev/null)"',
    '      COMPREPLY=( $(compgen -W "${keys}" -- "${cur}") )',
    "      return",
    "      ;;",
    "    --root)",
    '      COMPREPLY=( $(compgen -d -- "${cur}") )',
    "      return",
    "      ;;",
    "    *)",
    '      COMPREPLY=( $(compgen -W "${opts}" -- "${cur}") )',
    "      return",
    "      ;;",
    "  esac",
    "}",
    "",
    "complete -F _discover discover",
    "complete -F _discover bun",
  ];

  return `${lines.join("\n")}\n`;
}

function zshArgumentEntries(specs: readonly DiscoverCliOptionSpec[]): string[] {
  const entries: string[] = [];

  for (const spec of specs) {
    const flag = primaryLongFlag(spec);
    const short = spec.flags.find((entry) => entry.startsWith("-") && !entry.startsWith("--"));
    const desc = spec.description.replace(/'/g, "'\\''");

    if (spec.kind === "boolean") {
      const prefix = short ? `{${flag},${short}}` : flag;
      entries.push(`    '${prefix}[${desc}]'`);
    } else if (spec.kind === "value" && spec.key === "domain") {
      entries.push(`    '--domain[${desc}]:domain:_discover_domains'`);
    } else if (spec.kind === "value" && spec.key === "key") {
      entries.push(`    '--key[${desc}]:key:_discover_keys'`);
    } else if (spec.kind === "value" && spec.key === "root") {
      entries.push(`    '--root[${desc}]:directory:_directories'`);
    }
  }

  for (const spec of DISCOVER_CLI_META_SPECS) {
    const flag = spec.flags[0]!;
    const metaDesc = spec.description.replace(/'/g, "'\\''");
    if (flag === "--completion") {
      entries.push(`    '--completion[${metaDesc}]:shell:(bash zsh)'`);
    } else if (flag === "--complete-values") {
      entries.push(`    '--complete-values[${metaDesc}]:kind:(domain key)'`);
    }
  }

  entries.push("    '(-h --help)'{-h,--help}'[Show help]'");
  return entries;
}

export function formatDiscoverZshCompletion(
  specs: readonly DiscoverCliOptionSpec[],
  discoverCmd = "bun run discover"
): string {
  const args = zshArgumentEntries(specs).join("\n");
  const lines = [
    "#compdef discover",
    ...installHeader("zsh", discoverCmd),
    'local discover_cmd="${DISCOVER_CMD:-' + discoverCmd + '}"',
    "",
    "_discover_domains() {",
    "  local -a domains",
    '  domains=("${(@f)$(${=discover_cmd} --complete-values domain --root ${PWD} 2>/dev/null)}")',
    "  _describe 'define-domain' domains",
    "}",
    "",
    "_discover_keys() {",
    "  local -a keys",
    '  keys=("${(@f)$(${=discover_cmd} --complete-values key --root ${PWD} 2>/dev/null)}")',
    "  _describe 'define key' keys",
    "}",
    "",
    "_discover() {",
    "  _arguments -s -S \\",
    args,
    "}",
    "",
    "_discover",
  ];

  return `${lines.join("\n")}\n`;
}

export function formatDiscoverCliCompletion(
  shell: DiscoverShell,
  specs: readonly DiscoverCliOptionSpec[],
  discoverCmd = "bun run discover"
): string {
  return shell === "bash"
    ? formatDiscoverBashCompletion(specs, discoverCmd)
    : formatDiscoverZshCompletion(specs, discoverCmd);
}
