/**
 * Read-only Kimi Code config.toml audit — permissions and MCP tool rules.
 * Never writes config.toml; suggests templates only.
 * @see https://moonshotai.github.io/kimi-code/en/configuration/config-files.html
 */

import { join } from "path";
import { ensureDir } from "./utils.ts";
import { UNIFIED_SHELL_TOOL } from "./mcp-config.ts";
import { homeDir } from "./paths.ts";

const DEFAULT_PERMISSION_MODE = "manual";
const YOLO_MODE = "yolo";
const HOOK_TIMEOUT = 10;
const HOOK_EVENT = "PostToolUseFailure";
const HOOK_SCRIPT_NAME = "log-tool-failure.ts";
const SNIPPET_MARKER = "Kimi toolchain — unified-shell MCP permission";
const CONFIG_HEADER = "# Kimi Code config — generated by kimi-doctor --fix";
const UNIFIED_SHELL_WILDCARD = "mcp__unified-shell__*";

const PERMISSION_SNIPPET = `
# ${SNIPPET_MARKER} (uncomment to pre-approve)
# [[permission.rules]]
# decision = "allow"
# pattern = "${UNIFIED_SHELL_TOOL}"
`;

function configTomlPath(home: string = homeDir()): string {
  return join(home, ".kimi-code", "config.toml");
}

function hookSnippet(home: string): string {
  const hookPath = join(home, ".kimi-code", "kimi-hooks", HOOK_SCRIPT_NAME);
  return `
[[hooks]]
event = "${HOOK_EVENT}"
command = "bun run ${hookPath}"
timeout = ${HOOK_TIMEOUT}
`;
}

export interface PermissionRule {
  decision: string;
  pattern: string;
}

export interface ConfigAuditCheck {
  name: string;
  status: "ok" | "warn" | "error";
  message: string;
  fixable: boolean;
}

export function parsePermissionRules(text: string): PermissionRule[] {
  const rules: PermissionRule[] = [];
  const blocks = text.split(/\[\[permission\.rules\]\]/);
  for (const block of blocks.slice(1)) {
    const decision = block.match(/decision\s*=\s*"([^"]+)"/)?.[1];
    const pattern = block.match(/pattern\s*=\s*"([^"]+)"/)?.[1];
    if (decision && pattern) rules.push({ decision, pattern });
  }
  return rules;
}

export function parseDefaultPermissionMode(text: string): string {
  return text.match(/default_permission_mode\s*=\s*"([^"]+)"/)?.[1] ?? DEFAULT_PERMISSION_MODE;
}

export function allowsUnifiedShellMcp(rules: PermissionRule[]): boolean {
  for (const rule of rules) {
    if (rule.decision !== "allow") continue;
    if (rule.pattern === UNIFIED_SHELL_TOOL) return true;
    if (rule.pattern === UNIFIED_SHELL_WILDCARD) return true;
    if (rule.pattern.includes("unified-shell")) return true;
  }
  return false;
}

export async function auditKimiConfig(
  home: string = homeDir(),
  options: { unifiedShellRegistered?: boolean } = {}
): Promise<ConfigAuditCheck[]> {
  const checks: ConfigAuditCheck[] = [];
  const path = configTomlPath(home);
  const unifiedShellRegistered = options.unifiedShellRegistered ?? true;
  const exists = await Bun.file(path).exists();

  if (!exists) {
    checks.push({
      name: "config-toml",
      status: "warn",
      message: "missing — run kimi login; kimi-doctor --fix can seed permissions snippet",
      fixable: true,
    });
    if (unifiedShellRegistered) {
      checks.push({
        name: "mcp-permission",
        status: "warn",
        message: `cannot audit — config.toml missing (needs allow for ${UNIFIED_SHELL_TOOL})`,
        fixable: true,
      });
    }
    return checks;
  }

  checks.push({ name: "config-toml", status: "ok", message: path, fixable: false });

  const text = await Bun.file(path).text();
  const rules = parsePermissionRules(text);
  const mode = parseDefaultPermissionMode(text);
  const shellAllowed = allowsUnifiedShellMcp(rules);

  if (shellAllowed) {
    checks.push({
      name: "mcp-permission",
      status: "ok",
      message: `allow rule for ${UNIFIED_SHELL_TOOL}`,
      fixable: false,
    });
  } else if (unifiedShellRegistered) {
    checks.push({
      name: "mcp-permission",
      status: "warn",
      message: `no allow rule for ${UNIFIED_SHELL_TOOL} — run kimi-doctor --fix to append snippet`,
      fixable: true,
    });
  } else {
    checks.push({
      name: "mcp-permission",
      status: "ok",
      message: "unified-shell not registered — permission rule not required",
      fixable: false,
    });
  }

  if (mode === YOLO_MODE) {
    const msg = shellAllowed
      ? "default_permission_mode=yolo with explicit MCP allow"
      : "default_permission_mode=yolo — MCP shell may auto-approve without explicit allow rule";
    checks.push({
      name: "permission-mode",
      status: shellAllowed ? "ok" : "warn",
      message: msg,
      fixable: false,
    });
  } else {
    checks.push({
      name: "permission-mode",
      status: "ok",
      message: `default_permission_mode=${mode}`,
      fixable: false,
    });
  }

  if (text.includes(HOOK_EVENT) && text.includes(HOOK_SCRIPT_NAME)) {
    checks.push({
      name: "failure-hook",
      status: "ok",
      message: "PostToolUseFailure hook configured",
      fixable: false,
    });
  } else {
    checks.push({
      name: "failure-hook",
      status: "warn",
      message: "PostToolUseFailure hook not configured — run kimi-doctor --fix",
      fixable: true,
    });
  }

  // ── Loop control audit ───────────────────────────────────────────────
  const loopMatch = text.match(/\[loop_control\]\s*\n([\s\S]*?)(?=\n\[|\n*$)/);
  if (loopMatch) {
    const hasMaxSteps = loopMatch[1].includes("max_steps_per_turn");
    const maxStepsMatch = loopMatch[1].match(/max_steps_per_turn\s*=\s*(\d+)/);
    const maxSteps = maxStepsMatch ? parseInt(maxStepsMatch[1], 10) : undefined;

    if (hasMaxSteps && maxSteps !== undefined && maxSteps < 50) {
      checks.push({
        name: "loop-control",
        status: "warn",
        message: `max_steps_per_turn=${maxSteps} is low — AGENTS.md recommends unset for complex refactors; consider commenting out or raising to 100+`,
        fixable: true,
      });
    } else if (hasMaxSteps && maxSteps !== undefined && maxSteps >= 50) {
      checks.push({
        name: "loop-control",
        status: "ok",
        message: `max_steps_per_turn=${maxSteps} (adequate)`,
        fixable: false,
      });
    } else {
      checks.push({
        name: "loop-control",
        status: "ok",
        message: "max_steps_per_turn unset (recommended — unlimited for complex refactors)",
        fixable: false,
      });
    }

    const reservedMatch = loopMatch[1].match(/reserved_context_size\s*=\s*(\d+)/);
    const reserved = reservedMatch ? parseInt(reservedMatch[1], 10) : undefined;
    if (reserved !== undefined && reserved < 20000) {
      checks.push({
        name: "context-reserve",
        status: "warn",
        message: `reserved_context_size=${reserved} is low — compaction triggers too late; recommend 40000+`,
        fixable: true,
      });
    } else if (reserved !== undefined) {
      checks.push({
        name: "context-reserve",
        status: "ok",
        message: `reserved_context_size=${reserved}`,
        fixable: false,
      });
    }
  } else {
    checks.push({
      name: "loop-control",
      status: "warn",
      message: "no [loop_control] section found in config.toml",
      fixable: false,
    });
  }

  return checks;
}

interface MergeResult {
  merged: boolean;
  created: boolean;
  path: string;
}

async function mergeConfigSnippet(
  home: string,
  snippet: string,
  alreadyPresent: (text: string) => boolean
): Promise<MergeResult> {
  const path = configTomlPath(home);
  ensureDir(join(path, ".."));

  const exists = await Bun.file(path).exists();
  if (!exists) {
    await Bun.write(path, `${CONFIG_HEADER}\n${snippet}\n`);
    return { merged: true, created: true, path };
  }

  const text = await Bun.file(path).text();
  if (alreadyPresent(text)) {
    return { merged: false, created: false, path };
  }

  await Bun.write(path, text.trimEnd() + snippet + "\n");
  return { merged: true, created: false, path };
}

/** Idempotent merge — appends commented permission snippet; never overwrites existing config. */
export async function mergeConfigTomlPermissions(home: string = homeDir()): Promise<MergeResult> {
  const alreadyPresent = (text: string): boolean => {
    const rules = parsePermissionRules(text);
    if (allowsUnifiedShellMcp(rules)) return true;
    if (text.includes(UNIFIED_SHELL_TOOL)) return true;
    if (text.includes(SNIPPET_MARKER)) return true;
    return false;
  };
  return mergeConfigSnippet(home, PERMISSION_SNIPPET, alreadyPresent);
}

/** Idempotent merge — appends PostToolUseFailure hook snippet. */
export async function mergeConfigTomlHooks(home: string = homeDir()): Promise<MergeResult> {
  const alreadyPresent = (text: string): boolean =>
    text.includes(HOOK_EVENT) || text.includes(HOOK_SCRIPT_NAME);
  return mergeConfigSnippet(home, hookSnippet(home), alreadyPresent);
}
