/**
 * scaffold-modules.ts — KIMI_MODULES domain effect scaffolding for kimi-fix.
 *
 * Default: doctor (perf harness + perf-doctor CLI from examples/dashboard).
 */

import { join } from "path";
import { makeDir, pathExists } from "./bun-io.ts";

/** Modules scaffolded when KIMI_MODULES is unset. */
export const DEFAULT_KIMI_MODULES = ["doctor"] as const;

export type KimiModuleName = "doctor" | "image" | "trace" | "perf";

export function parseKimiModules(
  env: Record<string, string | undefined> = Bun.env
): KimiModuleName[] {
  const raw = (env.KIMI_MODULES ?? "").trim();
  if (!raw) return [...DEFAULT_KIMI_MODULES];
  return raw
    .split(",")
    .map((s) => s.trim().toLowerCase())
    .filter(Boolean) as KimiModuleName[];
}

export function toolchainRoot(): string {
  const dir = import.meta.dir;
  if (dir.includes("kimi-toolchain")) {
    return dir.split("kimi-toolchain")[0] + "kimi-toolchain";
  }
  return join(dir, "../..");
}

const DOCTOR_COPY_PATHS = [
  { from: "examples/dashboard/src/harness", to: "src/harness" },
  { from: "examples/dashboard/src/bin/perf-doctor.ts", to: "src/bin/perf-doctor.ts" },
  { from: "examples/dashboard/src/lib/isolation", to: "src/lib/isolation" },
  { from: "examples/dashboard/src/lib/symbols.ts", to: "src/lib/symbols.ts" },
  { from: "examples/dashboard/src/harness/__fixtures__", to: "src/harness/__fixtures__" },
] as const;

const DOCTOR_PACKAGE_SCRIPTS: Record<string, string> = {
  perf: "bun run src/bin/perf-doctor.ts --perf-gates --report",
  "perf:gates": "bun run src/bin/perf-doctor.ts --perf-gates",
  "perf:gates:changed":
    "bun run src/bin/perf-doctor.ts --perf-gates --changed-only --base=origin/main",
  "perf:train": "bun run src/bin/perf-doctor.ts --perf-gates --train --out=.",
  "perf:watch": "bun run src/bin/perf-doctor.ts --watch --perf-gates --report",
  "perf:nightly": "bun run src/bin/perf-doctor.ts --perf-gates --train --report --out=.",
};

const IMAGE_TEMPLATE = join("templates", "modules", "image", "src", "processor.ts");

export interface ScaffoldModulesResult {
  modules: string[];
  filesWritten: string[];
  skipped: string[];
}

async function copyTree(
  src: string,
  dest: string,
  dryRun: boolean,
  written: string[]
): Promise<void> {
  if (!pathExists(src)) return;
  const glob = new Bun.Glob("**/*");
  for await (const rel of glob.scan({ cwd: src, absolute: false, onlyFiles: true })) {
    const from = join(src, rel);
    const to = join(dest, rel);
    if (pathExists(to)) continue;
    if (!dryRun) {
      makeDir(join(to, ".."), { recursive: true });
      await Bun.write(to, Bun.file(from));
    }
    written.push(to);
  }
}

async function mergePackageScripts(
  project: string,
  scripts: Record<string, string>,
  dryRun: boolean
): Promise<void> {
  const pkgPath = join(project, "package.json");
  if (!pathExists(pkgPath)) return;
  const pkg = (await Bun.file(pkgPath).json()) as { scripts?: Record<string, string> };
  pkg.scripts = { ...pkg.scripts, ...scripts };
  if (!dryRun) await Bun.write(pkgPath, `${JSON.stringify(pkg, null, 2)}\n`);
}

function initTsContent(modules: string[]): string {
  const lines = [
    "/**",
    " * init.ts — KIMI_MODULES symbol registration (generated by kimi-fix).",
    " */",
    "",
  ];
  if (modules.includes("image")) {
    lines.push("import * as image from './effect/image/processor.ts';");
    lines.push("globalThis[Symbol.for('kimi.effect.image')] = image;");
    lines.push("");
  }
  if (modules.includes("doctor")) {
    lines.push("// doctor module: perf harness in src/harness — run `bun run perf:gates`");
    lines.push("");
  }
  return lines.join("\n");
}

export async function scaffoldKimiModules(
  project: string,
  modules: string[],
  dryRun: boolean
): Promise<ScaffoldModulesResult> {
  const root = toolchainRoot();
  const written: string[] = [];
  const skipped: string[] = [];

  for (const mod of modules) {
    if (mod === "doctor") {
      for (const { from, to } of DOCTOR_COPY_PATHS) {
        const src = join(root, from);
        const dest = join(project, to);
        if (!pathExists(src)) {
          skipped.push(`${mod}:${from} (source missing)`);
          continue;
        }
        await copyTree(src, dest, dryRun, written);
      }
      await mergePackageScripts(project, DOCTOR_PACKAGE_SCRIPTS, dryRun);
    }

    if (mod === "image") {
      const src = join(root, IMAGE_TEMPLATE);
      const dest = join(project, "src/effect/image/processor.ts");
      if (pathExists(dest)) {
        skipped.push("image:processor.ts");
      } else if (pathExists(src)) {
        if (!dryRun) {
          makeDir(join(dest, ".."), { recursive: true });
          await Bun.write(dest, Bun.file(src));
        }
        written.push(dest);
      }
    }
  }

  const initPath = join(project, "src/init.ts");
  if (!pathExists(initPath)) {
    if (!dryRun) {
      makeDir(join(project, "src"), { recursive: true });
      await Bun.write(initPath, initTsContent(modules));
    }
    written.push(initPath);
  }

  return { modules, filesWritten: written, skipped };
}
