import { describe, test, expect } from "bun:test";
import { join } from "path";
import { pathExists, readText } from "../src/lib/bun-io.ts";

const ROOT = join(import.meta.dir, "..");
const COMPLETIONS_DIR = join(ROOT, "completions");
const JSON_PATH = join(COMPLETIONS_DIR, "bun-cli.json");

async function runGenerator(): Promise<{
  exit: number;
  stdout: string;
  stderr: string;
}> {
  const proc = Bun.spawn(["bun", "run", "completions:generate"], {
    cwd: ROOT,
    stdout: "pipe",
    stderr: "pipe",
  });
  const exit = await proc.exited;
  const stdout = await Bun.readableStreamToText(proc.stdout);
  const stderr = await Bun.readableStreamToText(proc.stderr);
  return { exit, stdout, stderr };
}

describe("generate-cli-completions integration", () => {
  test("generates a valid completions/bun-cli.json", async () => {
    const { exit, stdout } = await runGenerator();
    expect(exit).toBe(0);
    expect(stdout).toContain("Generated CLI completion data at");

    expect(pathExists(JSON_PATH)).toBe(true);

    const raw = readText(JSON_PATH);
    const data = JSON.parse(raw);

    expect(data.version).toBeTypeOf("string");
    expect(data.referenceUrl).toBe("https://bun.com/reference");
    expect(Array.isArray(data.apiModules)).toBe(true);
    expect(data.apiModules.length).toBeGreaterThan(0);
    expect(Array.isArray(data.docs)).toBe(true);
    expect(data.docs.length).toBeGreaterThan(0);
    expect(typeof data.commands).toBe("object");
    expect(Object.keys(data.commands).length).toBeGreaterThan(10);
    expect(Array.isArray(data.globalFlags)).toBe(true);
    expect(data.globalFlags.length).toBeGreaterThan(0);

    const install = data.commands.install;
    expect(install).toBeDefined();
    expect(install.name).toBe("install");
    expect(Array.isArray(install.flags)).toBe(true);
    expect(install.flags.length).toBeGreaterThan(0);
    expect(install.docUrl).toMatch(/^https:\/\/bun\.com\/docs\//);
    expect(Array.isArray(install.sections)).toBe(true);
    expect(install.sections.length).toBeGreaterThan(0);

    const configSection = install.sections.find(
      (s: { anchor: string }) => s.anchor === "configuration"
    );
    expect(configSection).toBeDefined();
    expect(configSection.url).toMatch(/#configuration$/);
  });

  test("generates shell completion scripts", async () => {
    await runGenerator();

    for (const file of ["bun.bash", "bun.fish", "bun.zsh"]) {
      const p = join(COMPLETIONS_DIR, file);
      expect(pathExists(p)).toBe(true);
      const content = readText(p);
      expect(content.length).toBeGreaterThan(100);
      expect(content).toContain("Generated by scripts/generate-cli-completions.ts");
    }
  });

  test("includes dynamic completion wiring in bash and fish", async () => {
    await runGenerator();

    const bash = readText(join(COMPLETIONS_DIR, "bun.bash"));
    expect(bash).toContain("bun getcompletes s");
    expect(bash).toContain("bun getcompletes a");

    const fish = readText(join(COMPLETIONS_DIR, "bun.fish"));
    expect(fish).toContain("bun getcompletes s");
    expect(fish).toContain("bun getcompletes a");

    const zsh = readText(join(COMPLETIONS_DIR, "bun.zsh"));
    expect(zsh).toContain("_bun_scripts");
    expect(zsh).toContain("_bun_installed_packages");
  });
});
