#!/usr/bin/env bun
/**
 * deep-audit/report.ts — Render a deep-audit JSON report.
 *
 * Usage:
 *   bun run src/doctor/deep-audit/report.ts [.kimi-artifacts/deep-audit-report.json]
 *
 * Reads the report generated by kimi-deep-audit and prints a concise,
 * human-readable summary. Exit code mirrors the report's failed count.
 */

import { isDirectRun } from "../../lib/bun-utils.ts";
import type { DeepAuditReport } from "../../lib/deep-audit-types.ts";

function firstLine(text: string): string {
  return text.split("\n")[0]?.trim() ?? "";
}

async function renderReport(reportPath: string): Promise<number> {
  const file = Bun.file(reportPath);
  if (!(await file.exists())) {
    console.error(`Report not found: ${reportPath}`);
    return 1;
  }

  let report: DeepAuditReport;
  try {
    report = await file.json();
  } catch (err) {
    console.error(`Failed to parse report: ${err instanceof Error ? err.message : String(err)}`);
    return 1;
  }

  console.log(`\n── Deep Audit Report ─────────────────────────────────────`);
  console.log(`Generated: ${report.generatedAt}`);
  console.log(`Project:   ${report.projectRoot}`);
  console.log(`Bun:       ${report.bunVersion}`);
  console.log(`Mode:      ${report.full ? "full" : "default"}\n`);

  for (const run of report.runs) {
    const icon = run.ok ? "✅" : "❌";
    console.log(`${icon} ${run.id.padEnd(28)} ${run.summary} (${run.durationMs}ms)`);
  }

  console.log(`\n────────────────────────────────────────────────────────`);
  console.log(
    `Summary: ${report.summary.passed}/${report.summary.total} passed · ${report.summary.failed} failed · ${report.summary.durationMs}ms`
  );

  if (report.imageAudit) {
    const { filesScanned, findings } = report.imageAudit;
    console.log(`\nImage audit: ${filesScanned} file(s) scanned · ${findings.length} finding(s)`);
    for (const finding of findings) {
      console.log(`  [${finding.taxonomyId}] ${finding.file}: ${finding.message}`);
    }
  }

  if (report.summary.failed > 0) {
    console.log(`\nFailed audits:`);
    for (const run of report.runs) {
      if (!run.ok) {
        console.log(`  ❌ ${run.id}: exit ${run.exitCode}`);
        const firstErr = firstLine(run.stderr) || firstLine(run.stdout);
        if (firstErr) console.log(`     ${firstErr}`);
      }
    }
  }

  return report.summary.failed > 0 ? 1 : 0;
}

async function main(): Promise<number> {
  const reportPath = Bun.argv[2] ?? ".kimi-artifacts/deep-audit-report.json";
  return renderReport(reportPath);
}

if (isDirectRun(import.meta.path)) {
  const code = await main();
  if (code !== 0) process.exit(code);
}
