#!/usr/bin/env bun
/**
 * deep-audit/webview-report.ts — Render a deep-audit JSON report in a Bun.WebView window.
 *
 * Usage:
 *   bun run src/doctor/deep-audit/webview-report.ts [.kimi-artifacts/deep-audit-report.json]
 *
 * Reads the report generated by kimi-deep-audit, renders it as an HTML page, and opens
 * a native webview window. The HTML is written to .kimi-artifacts/deep-audit-report.html.
 */

import { isDirectRun } from "../../lib/bun-utils.ts";
import type { DeepAuditReport } from "../../lib/deep-audit-types.ts";
import { ensureDir } from "../../lib/utils.ts";
import { formatWebViewExperimentalNotice, webViewSupported } from "../../lib/webview-console.ts";
import { join } from "path";

function escapeScriptJson(report: DeepAuditReport): string {
  return JSON.stringify(report).replaceAll("<", "\\u003c");
}

export function renderReportHtml(report: DeepAuditReport): string {
  const passed = report.summary.passed;
  const failed = report.summary.failed;
  const total = report.summary.total;
  const statusClass = failed === 0 ? "success" : "failure";
  const statusIcon = failed === 0 ? "✅" : "❌";
  const maxDuration = Math.max(...report.runs.map((r) => r.durationMs), 1);

  const rows = report.runs
    .map((run) => {
      const widthPct = ((run.durationMs / maxDuration) * 100).toFixed(1);
      return `
    <tr class="run ${run.ok ? "pass" : "fail"}">
      <td class="icon">${run.ok ? "✅" : "❌"}</td>
      <td class="id">${Bun.escapeHTML(run.id)}</td>
      <td class="summary">
        <div class="summary-text">${Bun.escapeHTML(run.summary)}</div>
        <div class="duration-bar-bg" aria-hidden="true">
          <div class="duration-bar" style="width: ${widthPct}%"></div>
        </div>
      </td>
      <td class="duration">${run.durationMs}ms</td>
    </tr>
    <tr class="details ${run.ok ? "pass" : "fail"}">
      <td colspan="4">
        <details>
          <summary>Details</summary>
          <div class="detail-grid">
            <div><strong>Exit code:</strong> ${run.exitCode}</div>
            <div><strong>Description:</strong> ${Bun.escapeHTML(run.description)}</div>
          </div>
          ${run.stdout ? `<div class="output"><strong>stdout</strong><pre><code>${Bun.escapeHTML(run.stdout)}</code></pre></div>` : ""}
          ${run.stderr ? `<div class="output"><strong>stderr</strong><pre><code>${Bun.escapeHTML(run.stderr)}</code></pre></div>` : ""}
        </details>
      </td>
    </tr>`;
    })
    .join("");

  const imageAuditRows = report.imageAudit?.findings.length
    ? report.imageAudit.findings
        .map(
          (finding) => `
    <tr>
      <td class="taxonomy">${Bun.escapeHTML(finding.taxonomyId)}</td>
      <td class="file">${Bun.escapeHTML(finding.file)}</td>
      <td class="message">${Bun.escapeHTML(finding.message)}</td>
    </tr>`
        )
        .join("")
    : "";

  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>Deep Audit Report — ${Bun.escapeHTML(report.projectRoot)}</title>
  <style>
    :root {
      --bg: #0d1117;
      --surface: #161b22;
      --border: #30363d;
      --text: #c9d1d9;
      --muted: #8b949e;
      --success: #3fb950;
      --danger: #f85149;
      --accent: #58a6ff;
      --font: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
    }
    @media (prefers-color-scheme: light) {
      :root {
        --bg: #ffffff;
        --surface: #f6f8fa;
        --border: #d0d7de;
        --text: #24292f;
        --muted: #57606a;
      }
    }
    * { box-sizing: border-box; }
    body {
      margin: 0;
      font-family: var(--font);
      background: var(--bg);
      color: var(--text);
      line-height: 1.5;
    }
    header, main { padding: 2rem; max-width: 1100px; margin: 0 auto; }
    header {
      border-bottom: 1px solid var(--border);
      position: sticky;
      top: 0;
      background: var(--bg);
      z-index: 10;
    }
    h1 { margin: 0 0 0.25rem; font-size: 1.75rem; }
    .meta { color: var(--muted); font-size: 0.875rem; }
    .status {
      display: inline-flex;
      align-items: center;
      gap: 0.5rem;
      margin-top: 1rem;
      padding: 0.75rem 1rem;
      border-radius: 0.5rem;
      font-weight: 600;
      background: var(--surface);
      border: 1px solid var(--border);
    }
    .status.success { border-color: var(--success); color: var(--success); }
    .status.failure { border-color: var(--danger); color: var(--danger); }
    .toolbar {
      display: flex;
      gap: 0.75rem;
      margin-bottom: 1.5rem;
      flex-wrap: wrap;
      align-items: center;
    }
    .toolbar input[type="search"] {
      flex: 1 1 16rem;
      padding: 0.5rem 0.75rem;
      border-radius: 0.375rem;
      border: 1px solid var(--border);
      background: var(--surface);
      color: var(--text);
      font: inherit;
    }
    .toolbar button {
      padding: 0.5rem 0.75rem;
      border-radius: 0.375rem;
      border: 1px solid var(--border);
      background: var(--surface);
      color: var(--text);
      font: inherit;
      cursor: pointer;
    }
    .toolbar button:hover { background: var(--border); }
    table {
      width: 100%;
      border-collapse: collapse;
      background: var(--surface);
      border: 1px solid var(--border);
      border-radius: 0.5rem;
      overflow: hidden;
    }
    th, td { padding: 0.75rem 1rem; text-align: left; border-bottom: 1px solid var(--border); }
    th { font-weight: 600; color: var(--muted); font-size: 0.875rem; text-transform: uppercase; letter-spacing: 0.025em; }
    tr.run { cursor: pointer; }
    tr.run:hover { filter: brightness(1.15); }
    tr.details td { padding: 0; border-bottom: 1px solid var(--border); }
    tr.details:last-child td { border-bottom: none; }
    tr.pass .icon { color: var(--success); }
    tr.fail .icon { color: var(--danger); }
    tr.fail .id { font-weight: 600; }
    .id { font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace; font-size: 0.875rem; }
    .duration { text-align: right; font-variant-numeric: tabular-nums; color: var(--muted); white-space: nowrap; }
    .summary { color: var(--text); width: 60%; }
    .summary-text { margin-bottom: 0.25rem; }
    .duration-bar-bg {
      height: 0.25rem;
      background: var(--border);
      border-radius: 0.125rem;
      overflow: hidden;
    }
    .duration-bar {
      height: 100%;
      background: var(--accent);
      border-radius: 0.125rem;
      min-width: 2px;
    }
    details { padding: 0.75rem 1rem; }
    summary {
      cursor: pointer;
      color: var(--accent);
      font-weight: 600;
      user-select: none;
    }
    summary:hover { text-decoration: underline; }
    .detail-grid {
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(12rem, 1fr));
      gap: 0.5rem;
      margin: 0.75rem 0;
      font-size: 0.875rem;
    }
    .output { margin-top: 0.75rem; }
    .output strong { color: var(--muted); font-size: 0.75rem; text-transform: uppercase; }
    pre {
      margin: 0.25rem 0 0;
      padding: 0.75rem;
      background: var(--bg);
      border: 1px solid var(--border);
      border-radius: 0.375rem;
      overflow-x: auto;
      font-size: 0.8125rem;
      line-height: 1.4;
      white-space: pre-wrap;
      word-break: break-word;
    }
    .summary-line { margin-top: 1.5rem; font-size: 1.125rem; }
    .summary-line strong { color: var(--accent); }
    .image-audit { margin-top: 2rem; }
    .image-audit h2 { font-size: 1.25rem; margin-bottom: 0.5rem; }
    .image-audit .meta { margin-bottom: 1rem; }
    .taxonomy {
      font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace;
      font-size: 0.875rem;
      color: var(--muted);
    }
    .file {
      font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace;
      font-size: 0.875rem;
    }
    .message { color: var(--text); }
    .empty-state { color: var(--muted); font-style: italic; }
  </style>
</head>
<body>
  <header>
    <h1>Deep Audit Report</h1>
    <div class="meta">
      <div>Project: ${Bun.escapeHTML(report.projectRoot)}</div>
      <div>Generated: ${Bun.escapeHTML(report.generatedAt)}</div>
      <div>Bun: ${Bun.escapeHTML(report.bunVersion)} · Mode: ${report.full ? "full" : "default"}</div>
    </div>
    <div class="status ${statusClass}">
      ${statusIcon} ${passed}/${total} passed · ${failed} failed · ${report.summary.durationMs}ms
    </div>
  </header>
  <main>
    <div class="toolbar">
      <input type="search" id="run-search" placeholder="Filter audits by id or result..." aria-label="Filter audits" />
      <button id="download-json" type="button">Download JSON</button>
    </div>
    <table>
      <thead>
        <tr>
          <th style="width: 2.5rem"></th>
          <th>Audit</th>
          <th>Result</th>
          <th style="width: 6rem; text-align: right">Time</th>
        </tr>
      </thead>
      <tbody>
        ${rows}
      </tbody>
    </table>
    ${
      report.imageAudit
        ? `
    <section class="image-audit">
      <h2>Image Audit</h2>
      <p class="meta">${report.imageAudit.filesScanned} file(s) scanned · ${report.imageAudit.findings.length} finding(s)</p>
      ${
        imageAuditRows
          ? `
      <table>
        <thead>
          <tr>
            <th>Taxonomy</th>
            <th>File</th>
            <th>Message</th>
          </tr>
        </thead>
        <tbody>
          ${imageAuditRows}
        </tbody>
      </table>`
          : `<p class="summary-line">No findings.</p>`
      }
    </section>`
        : ""
    }
    <p class="summary-line">
      Total audits: <strong>${total}</strong> · Passed: <strong>${passed}</strong> · Failed: <strong>${failed}</strong>
    </p>
  </main>
  <script type="application/json" id="report-data">${escapeScriptJson(report)}</script>
  <script>
    (function () {
      const reportData = JSON.parse(document.getElementById("report-data").textContent);

      document.getElementById("download-json").addEventListener("click", function () {
        const blob = new Blob([JSON.stringify(reportData, null, 2)], { type: "application/json" });
        const url = URL.createObjectURL(blob);
        const a = document.createElement("a");
        a.href = url;
        a.download = "deep-audit-report.json";
        document.body.appendChild(a);
        a.click();
        a.remove();
        URL.revokeObjectURL(url);
      });

      document.getElementById("run-search").addEventListener("input", function (e) {
        const term = e.target.value.toLowerCase();
        const runRows = document.querySelectorAll("tbody tr.run");
        runRows.forEach(function (row) {
          const id = row.querySelector(".id")?.textContent.toLowerCase() ?? "";
          const summary = row.querySelector(".summary-text")?.textContent.toLowerCase() ?? "";
          const match = id.includes(term) || summary.includes(term);
          row.style.display = match ? "" : "none";
          const details = row.nextElementSibling;
          if (details && details.classList.contains("details")) {
            details.style.display = match ? "" : "none";
          }
        });
      });

      document.querySelectorAll("tbody tr.run").forEach(function (row) {
        row.addEventListener("click", function () {
          const details = row.nextElementSibling;
          if (details && details.classList.contains("details")) {
            const detailsEl = details.querySelector("details");
            if (detailsEl) detailsEl.open = !detailsEl.open;
          }
        });
      });
    })();
  </script>
</body>
</html>`;
}

async function writeHtmlReport(report: DeepAuditReport): Promise<string> {
  const artifactsDir = join(report.projectRoot, ".kimi-artifacts");
  ensureDir(artifactsDir);
  const htmlPath = join(artifactsDir, "deep-audit-report.html");
  await Bun.write(htmlPath, renderReportHtml(report));
  return htmlPath;
}

async function openWebviewReport(htmlPath: string): Promise<Bun.WebView> {
  if (!webViewSupported()) {
    throw new Error("Bun.WebView is not available in this runtime");
  }

  process.stderr.write(`${formatWebViewExperimentalNotice()}\n`);

  const view = new Bun.WebView({
    width: 1024,
    height: 768,
  });

  await view.navigate(Bun.pathToFileURL(htmlPath).href);
  return view;
}

/**
 * Block until SIGINT/SIGTERM, then close the webview. Call after printing any
 * confirmation messages so the user sees them before the blocking wait.
 */
export async function waitForWebviewClose(view: Bun.WebView): Promise<void> {
  await new Promise<void>((resolve) => {
    process.once("SIGINT", () => {
      view.close();
      resolve();
    });
    process.once("SIGTERM", () => {
      view.close();
      resolve();
    });
  });
}

export async function showWebviewReport(
  report: DeepAuditReport
): Promise<{ htmlPath: string; view: Bun.WebView }> {
  const htmlPath = await writeHtmlReport(report);
  const view = await openWebviewReport(htmlPath);
  return { htmlPath, view };
}

async function main(): Promise<number> {
  try {
    const reportPath = Bun.argv[2] ?? ".kimi-artifacts/deep-audit-report.json";
    const file = Bun.file(reportPath);
    if (!(await file.exists())) {
      console.error(`Report not found: ${reportPath}`);
      return 1;
    }
    const report = (await file.json()) as DeepAuditReport;
    const htmlPath = await writeHtmlReport(report);
    console.log(`HTML report written to ${htmlPath}`);
    const view = await openWebviewReport(htmlPath);
    console.log("Webview opened. Press Ctrl+C to close.");
    await waitForWebviewClose(view);
    return 0;
  } catch (err) {
    console.error("[fatal]", err instanceof Error ? err.message : err);
    return 1;
  }
}

if (isDirectRun(import.meta.path)) {
  const code = await main();
  if (code !== 0) process.exit(code);
}
