/**
 * Compile-time constants injected by Bun from `bunfig.toml` `[define]`.
 *
 * Naming layers (do not conflate):
 * - **define constant** — `KIMI_{DOMAIN}_{QUALIFIER}` SCREAMING_SNAKE globals below
 * - **defineDomain** — kebab-case slice label in bunfig (`# define-domain:...`) and `@defineDomain` JSDoc
 * - **taxonomyId** — snake_case failure class in `error-taxonomy.yml` (runtime, not define)
 *
 * SSOT: edit values in bunfig only — do not duplicate literals in source.
 * Discovery: `constants-manifest.json` (generated by `bun run manifest:generate`).
 * Regression: `bun run scripts/lint-build-constants.ts` (wired into `lint`).
 *
 * @see bunfig.toml `[define]`
 * @see scripts/lint-build-constants.ts
 * @see test/build-constants.unit.test.ts
 * @see CODE_REFERENCES.md § Build-time constants
 */

/**
 * @defineDomain contract-inference
 * @type string
 * @default ".kimi/var/contract-observations.ndjson"
 * @restrictions must be a relative path from project root
 * @see src/lib/paths.ts contractObservationsPath
 */
declare const KIMI_CONTRACT_OBSERVATIONS_PATH: string;

/**
 * @defineDomain contract-inference
 * @type string
 * @default "1.0.0"
 * @restrictions semver string written/read by contract inference
 * @see src/lib/contract-inference.ts
 */
declare const KIMI_CONTRACT_SCHEMA_VERSION: string;

/**
 * @defineDomain contract-inference
 * @type boolean
 * @default true
 * @restrictions when false, inferContractFromObservations skips work
 */
declare const KIMI_CONTRACT_INFERENCE_ENABLED: boolean;

/**
 * @defineDomain hook-verifier
 * @type number
 * @default 32
 * @restrictions positive integer — max allowed hook-graph cycle length
 * @see src/lib/hook-verifier.ts
 */
declare const KIMI_HOOK_VERIFIER_MAX_CYCLES: number;

/**
 * @defineDomain error-embedding
 * @type number
 * @default 384
 * @restrictions reserved — embedding vector width (Phase 2)
 * @see src/lib/error-embedding.ts
 */
declare const KIMI_ERROR_EMBEDDING_DIM: number;

/**
 * @defineDomain decision-scoring
 * @type number
 * @default 7
 * @restrictions positive integer — decision score rolling window in days (Phase 2)
 * @see constants-parity.toml shared id velocity-window-days
 * @see src/lib/decision-scoring.ts
 */
declare const KIMI_DECISION_SCORE_WINDOW_DAYS: number;

/**
 * @defineDomain optimizer
 * @type number
 * @default 30
 * @restrictions positive integer — linear decay window for insufficient-data confidence (Phase 3.2)
 * @see src/lib/constant-optimizer.ts
 */
declare const KIMI_OPTIMIZER_CONFIDENCE_DECAY_DAYS: number;

/**
 * @defineDomain error-clustering
 * @type number
 * @default 0.55
 * @restrictions reserved — cluster merge threshold in [0, 1] (Phase 2)
 * @see src/lib/error-clustering.ts
 */
declare const KIMI_ERROR_CLUSTER_SIMILARITY_THRESHOLD: number;

/**
 * @defineDomain runtime
 * @type string
 * @default "1.3.14"
 * @restrictions semver — minimum Bun runtime version required by toolchain tooling
 */
declare const KIMI_RUNTIME_MIN_BUN_VERSION: string;

/**
 * @defineDomain runtime
 * @type string
 * @default "source"
 * @restrictions one of source | release | canary — identifies how CLI binaries were built
 */
declare const KIMI_RUNTIME_CLI_BUILD_CHANNEL: string;

/**
 * @defineDomain dashboard
 * @type boolean
 * @default true
 * @restrictions boolean flag — when false, dashboard live refresh is disabled
 */
declare const KIMI_DASHBOARD_LIVE_REFRESH_ENABLED: boolean;

/**
 * @defineDomain governance
 * @type string
 * @default "1.2.0"
 * @restrictions semver — bump when any other KIMI_* define is added, changed, or removed
 * @see scripts/lint-tuning-set-version.ts
 */
declare const KIMI_TUNING_SET_VERSION: string;
