/**
 * Compile-time constants injected by Bun from `bunfig.toml` `[define]`.
 *
 * Naming layers (do not conflate):
 * - **define constant** — `KIMI_{DOMAIN}_{QUALIFIER}` SCREAMING_SNAKE globals below
 * - **defineDomain** — kebab-case slice label in bunfig (`# define-domain:...`) and `@defineDomain` JSDoc
 * - **taxonomyId** — snake_case failure class in `error-taxonomy.yml` (runtime, not define)
 *
 * SSOT: edit values in bunfig only — do not duplicate literals in source.
 * Discovery: `constants-manifest.json` (generated by `bun run manifest:generate`).
 * Regression: `bun run lint:defines` validates that every `[define]` value is valid JSON.
 *
 * @see bunfig.toml `[define]`
 * @see https://bun.com/guides/runtime/build-time-constants
 * @see scripts/lint-build-constants.ts
 * @see test/build-constants.unit.test.ts
 * @see CODE_REFERENCES.md § Build-time constants
 */

/**
 * @defineDomain contract-inference
 * @type string
 * @default ".kimi/var/contract-observations.ndjson"
 * @restrictions must be a relative path from project root
 * @see src/lib/paths.ts contractObservationsPath
 */
declare const KIMI_CONTRACT_OBSERVATIONS_PATH: string;

/**
 * @defineDomain contract-inference
 * @type string
 * @default "1.0.0"
 * @restrictions semver string written/read by contract inference
 * @see src/lib/contract-inference.ts
 */
declare const KIMI_CONTRACT_SCHEMA_VERSION: string;

/**
 * @defineDomain contract-inference
 * @type boolean
 * @default true
 * @restrictions when false, inferContractFromObservations skips work
 */
declare const KIMI_CONTRACT_INFERENCE_ENABLED: boolean;

/**
 * @defineDomain hook-verifier
 * @type number
 * @default 32
 * @restrictions positive integer — max allowed hook-graph cycle length
 * @see src/lib/hook-verifier.ts
 */
declare const KIMI_HOOK_VERIFIER_MAX_CYCLES: number;

/**
 * @defineDomain error-embedding
 * @type number
 * @default 384
 * @restrictions reserved — embedding vector width (Phase 2)
 * @see src/lib/error-embedding.ts
 */
declare const KIMI_ERROR_EMBEDDING_DIM: number;

/**
 * @defineDomain decision-scoring
 * @type number
 * @default 7
 * @restrictions positive integer — decision score rolling window in days (Phase 2)
 * @see constants-parity.toml shared id velocity-window-days
 * @see src/lib/decision-scoring.ts
 */
declare const KIMI_DECISION_SCORE_WINDOW_DAYS: number;

/**
 * @defineDomain optimizer
 * @type number
 * @default 30
 * @restrictions positive integer — linear decay window for insufficient-data confidence (Phase 3.2)
 * @see src/lib/constant-optimizer.ts
 */
declare const KIMI_OPTIMIZER_CONFIDENCE_DECAY_DAYS: number;

/**
 * @defineDomain error-clustering
 * @type number
 * @default 0.55
 * @restrictions reserved — cluster merge threshold in [0, 1] (Phase 2)
 * @see src/lib/error-clustering.ts
 */
declare const KIMI_ERROR_CLUSTER_SIMILARITY_THRESHOLD: number;

/**
 * @defineDomain runtime
 * @type string
 * @default "1.4.0"
 * @restrictions semver — minimum Bun runtime version required by toolchain tooling
 */
declare const KIMI_RUNTIME_MIN_BUN_VERSION: string;

/**
 * @defineDomain runtime
 * @type string
 * @default "source"
 * @restrictions one of source | release | canary — identifies how CLI binaries were built
 */
declare const KIMI_RUNTIME_CLI_BUILD_CHANNEL: string;

/**
 * @defineDomain dashboard
 * @type boolean
 * @default true
 * @restrictions boolean flag — when false, dashboard live refresh is disabled
 */
declare const KIMI_DASHBOARD_LIVE_REFRESH_ENABLED: boolean;

/**
 * @defineDomain effect-discipline
 * @type number
 * @default 0
 * @restrictions zero-tolerance threshold for bare Promise usage in service code
 * @see src/lib/effect-gates.ts
 */
declare const KIMI_EFFECT_MAX_DIRECT_PROMISE: number;

/**
 * @defineDomain effect-discipline
 * @type string
 * @default "strict"
 * @restrictions one of strict | gradual | off
 * @see src/lib/effect-gates.ts
 */
declare const KIMI_DOMAIN_PURITY_LEVEL: "strict" | "gradual" | "off";

/**
 * @defineDomain effect-discipline
 * @type number
 * @default 0
 * @restrictions zero-tolerance threshold for circular layer dependencies
 * @see src/lib/effect-gates.ts
 */
declare const KIMI_LAYER_CIRCULARITY_TOLERANCE: number;

/**
 * @defineDomain effect-discipline
 * @type boolean
 * @default true
 * @restrictions when true, exported services must be provided through Tag + Layer
 * @see src/lib/effect-gates.ts
 */
declare const KIMI_SERVICE_TAG_REQUIRED: boolean;

/**
 * @defineDomain effect-discipline
 * @type boolean
 * @default true
 * @restrictions when true, Effect.runPromise calls outside src/cli, src/entry, src/runtime.ts, or test files are flagged
 * @see src/lib/effect-gates.ts
 */
declare const KIMI_EFFECT_RUN_PROMISE_BOUNDARY_ENABLED: boolean;

/**
 * @defineDomain effect-benchmark
 * @type number
 * @default 5
 * @restrictions positive integer — measured iterations per effect handler
 * @see src/lib/effect-benchmark.ts
 */
declare const KIMI_EFFECT_BENCHMARK_ITERATIONS: number;

/**
 * @defineDomain effect-benchmark
 * @type number
 * @default 2
 * @restrictions non-negative integer — warmup iterations discarded before measurement
 * @see src/lib/effect-benchmark.ts
 */
declare const KIMI_EFFECT_BENCHMARK_WARMUP: number;

/**
 * @defineDomain effect-benchmark
 * @type number
 * @default 1.1
 * @restrictions multiplier >= 1.0 — trained threshold margin over measured median
 * @see src/lib/effect-benchmark.ts
 */
declare const KIMI_EFFECT_BENCHMARK_TRAIN_MARGIN: number;

/**
 * @defineDomain effect-benchmark
 * @type number
 * @default 1.05
 * @restrictions multiplier >= 1.0 — regression tolerance when comparing to previous snapshot
 * @see src/lib/effect-benchmark.ts
 */
declare const KIMI_EFFECT_BENCHMARK_REGRESSION_TOLERANCE: number;

/**
 * @defineDomain effect-benchmark
 * @type number
 * @default 100
 * @restrictions positive number — fallback threshold (ms) for handlers without a default
 * @see src/lib/effect-benchmark.ts
 */
declare const KIMI_EFFECT_BENCHMARK_DEFAULT_THRESHOLD_MS: number;

/**
 * @defineDomain effect-benchmark
 * @type number
 * @default 50
 * @restrictions positive integer — max NDJSON snapshot rows retained per project
 * @see src/lib/effect-benchmark.ts
 */
declare const KIMI_EFFECT_BENCHMARK_SNAPSHOT_MAX_RUNS: number;

/**
 * @defineDomain effect-benchmark
 * @type number
 * @default 10000
 * @restrictions positive integer — max wall-clock ms for a dashboard benchmark run
 * @see src/lib/effect-benchmark.ts
 */
declare const KIMI_EFFECT_BENCHMARK_RUN_TIMEOUT_MS: number;

/**
 * @defineDomain effect-benchmark
 * @type number
 * @default 8000
 * @restrictions positive integer — min ms between POST refresh/train requests
 * @see src/lib/effect-benchmark-resilience.ts
 */
declare const KIMI_EFFECT_BENCHMARK_POST_COOLDOWN_MS: number;

/**
 * @defineDomain governance
 * @type string
 * @default "1.4.5"
 * @restrictions semver — bump when any other KIMI_* define is added, changed, or removed
 * @see scripts/lint-tuning-set-version.ts
 */
declare const KIMI_TUNING_SET_VERSION: string;

/**
 * @defineDomain mcp-defaults
 * @type object
 * @default {"callTimeoutMs":60000,"queryTimeoutMs":30000,"cardTimeoutMs":15000,"maxTop":0}
 * @restrictions JSON object; maxTop 0 means no default truncation
 * @see src/lib/mcp-config.ts
 * @see src/bin/kimi-mcp.ts
 */
declare const KIMI_MCP_DEFAULTS:
  | {
      callTimeoutMs: number;
      queryTimeoutMs: number;
      cardTimeoutMs: number;
      maxTop: number;
    }
  | undefined;
