/**
 * Flag taxonomy for Bun CLI completion analysis.
 *
 * These categories classify flags by behavior. They are consumed by
 * src/completions/completion-matrix.ts and validated by
 * src/completions/taxonomy-validator.ts using Bun.Transpiler.
 */

export const FLAG_CATEGORIES = {
  fileIO: new Set([
    "outfile",
    "outdir",
    "outbase",
    "entry-naming",
    "chunk-naming",
    "asset-naming",
    "public-dir",
    "assets",
    "loader",
    "tsconfig-override",
    "cwd",
    "config",
    "env-file",
    "cafile",
    "cache-dir",
    "public",
    "routes",
    "app",
    "external",
    "packages",
    "target",
    "sourcemap",
    "minify",
    "splitting",
    "format",
    "patches-dir",
    "public-path",
    "root",
  ]),
  pm: new Set([
    "frozen-lockfile",
    "production",
    "development",
    "dev",
    "no-save",
    "save",
    "global",
    "trust",
    "no-trust",
    "exact",
    "optional",
    "peer",
    "resolutions",
    "hoist",
    "no-hoist",
    "linker",
    "omit",
    "backend",
    "concurrent-scripts",
    "network-concurrency",
    "registry",
    "auth-type",
    "tag",
    "access",
    "dry-run",
    "no-cache",
    "prefer-offline",
    "no-verify",
    "ignore-scripts",
    "no-summary",
    "no-progress",
    "no-install",
    "save-text-lockfile",
    "lockfile-only",
    "minimum-release-age",
    "force",
    "only-missing",
    "yarn",
    "latest",
    "otp",
    "os",
    "package",
    "tolerate-republish",
    "commit",
    "yes",
    "install",
    "i",
    "audit-level",
    "cpu",
    "analyze",
  ]),
  runtime: new Set([
    "watch",
    "hot",
    "preload",
    "import-meta-url",
    "smol",
    "no-deprecation",
    "throw-deprecation",
    "env-file",
    "cwd",
    "port",
    "hostname",
    "conditions",
    "main-fields",
    "extensions",
    "target",
    "format",
    "packages",
    "no-orphans",
    "no-clear-screen",
    "parallel",
    "sequential",
    "no-exit-on-error",
    "workspaces",
    "filter",
    "bun",
    "interactive",
    "shell",
    "unhandled-rejections",
    "zero-fill-buffers",
    "no-env-file",
    "eval",
    "experimental-http2-fetch",
    "experimental-http3-fetch",
    "experimental-stream-iter",
    "fetch-preconnect",
    "redis-preconnect",
    "sql-preconnect",
    "server-components",
    "cron-period",
    "cron-title",
    "feature",
    "recursive",
    "if-present",
    "prefer-latest",
  ]),
  debug: new Set([
    "sourcemap",
    "inspect",
    "inspect-wait",
    "inspect-brk",
    "inspect-publish-port",
    "verbose",
    "silent",
    "quiet",
    "no-progress",
    "no-summary",
    "only-failures",
    "coverage",
    "coverage-reporter",
    "coverage-dir",
    "cpu-prof",
    "revision",
    "version",
    "help",
    "console-depth",
    "debug-no-minify",
    "debug-dump-server-files",
    "elide-lines",
  ]),
  network: new Set([
    "timeout",
    "prefer-offline",
    "no-cache",
    "registry",
    "cert",
    "ca",
    "cafile",
    "auth-type",
    "proxy",
    "network-concurrency",
    "no-verify",
    "tls-min-version",
    "tls-max-version",
    "no-deprecation",
    "max-http-header-size",
    "dns-result-order",
    "user-agent",
    "use-bundled-ca",
    "use-openssl-ca",
    "use-system-ca",
  ]),
  compile: new Set([
    "compile",
    "compile-autoload-bunfig",
    "compile-autoload-dotenv",
    "compile-autoload-package-json",
    "compile-autoload-tsconfig",
    "compile-exec-argv",
    "compile-executable-path",
    "no-compile-autoload-bunfig",
    "no-compile-autoload-dotenv",
    "no-compile-autoload-package-json",
    "no-compile-autoload-tsconfig",
    "bytecode",
    "no-bundle",
    "minify-identifiers",
    "minify-syntax",
    "minify-whitespace",
    "drop",
    "keep-names",
    "banner",
    "footer",
    "define",
    "metafile",
    "metafile-md",
    "emit-dce-annotations",
    "ignore-dce-annotations",
    "allow-unresolved",
    "reject-unresolved",
    "no-addons",
    "no-macros",
    "minimal",
    "css-chunking",
    "gzip-level",
    "env",
    "production",
  ]),
  test: new Set([
    "bail",
    "test-name-pattern",
    "test-worker",
    "pass-with-no-tests",
    "rerun-each",
    "randomize",
    "seed",
    "shard",
    "todo",
    "only",
    "retry",
    "update-snapshots",
    "dots",
    "title",
    "ignore",
    "path-ignore-patterns",
    "reporter",
    "reporter-outfile",
    "isolate",
    "concurrent",
    "max-concurrency",
    "parallel-delay",
    "changed",
  ]),
  jsx: new Set([
    "jsx-factory",
    "jsx-fragment",
    "jsx-import-source",
    "jsx-runtime",
    "jsx-side-effects",
    "react",
    "react-compiler",
    "react-fast-refresh",
  ]),
  profiling: new Set([
    "cpu-prof",
    "cpu-prof-dir",
    "cpu-prof-interval",
    "cpu-prof-md",
    "cpu-prof-name",
    "heap-prof",
    "heap-prof-dir",
    "heap-prof-md",
    "heap-prof-name",
    "expose-gc",
  ]),
  windows: new Set([
    "windows-copyright",
    "windows-description",
    "windows-hide-console",
    "windows-icon",
    "windows-publisher",
    "windows-title",
    "windows-version",
  ]),
  resolution: new Set([
    "extension-order",
    "preserve-symlinks",
    "preserve-symlinks-main",
    "import",
    "require",
  ]),
  output: new Set([
    "json",
    "print",
  ]),
} as const;

export type FlagCategory = keyof typeof FLAG_CATEGORIES | "uncategorized";

/**
 * Validate the taxonomy for obvious structural issues:
 * - no empty category names
 * - no empty flag names
 * - no flag names containing whitespace
 * - no empty category sets
 */
export function findStructuralIssues(): {
  kind: string;
  category?: string;
  flag?: string;
}[] {
  const issues: { kind: string; category?: string; flag?: string }[] = [];
  for (const [category, flags] of Object.entries(FLAG_CATEGORIES)) {
    if (category.trim() === "") {
      issues.push({ kind: "empty-category-name" });
      continue;
    }
    if (flags.size === 0) {
      issues.push({ kind: "empty-category", category });
    }
    for (const flag of flags) {
      if (flag.trim() === "") {
        issues.push({ kind: "empty-flag-name", category });
      } else if (/\s/.test(flag)) {
        issues.push({ kind: "flag-contains-whitespace", category, flag });
      }
    }
  }
  return issues;
}
