#!/usr/bin/env bun
/**
 * template-bootstrap: global install + kimi-fix run before project secrets registry exists.
 * kimi-toolchain template postinstall.
 *
 * Usage:
 *   bun run scripts/postinstall.ts
 *   bun run scripts/postinstall.ts --with-secrets
 *   bun run scripts/postinstall.ts --with-secrets --secrets "github-token,npm-token"
 *   bun run scripts/postinstall.ts --help
 */

import { parseArgs } from "util";
import { join } from "path";

const { values } = parseArgs({
  args: Bun.argv,
  options: {
    "with-secrets": { type: "boolean", default: false },
    service: { type: "string" },
    domain: { type: "string", default: "com.kimi" },
    secrets: { type: "string", default: "api-key,db-url" },
  },
  strict: false,
  allowPositionals: true,
});

function deriveServiceName(): string {
  const base = process.cwd().split("/").pop() ?? "toolchain";
  const sanitized = base
    .replace(/[^a-zA-Z0-9_-]/g, "-")
    .replace(/^-+|-+$/g, "")
    .toLowerCase();
  return sanitized || "toolchain";
}

const DEST = process.cwd();
const HOME = Bun.env.KIMI_SCAFFOLD_HOME ?? Bun.env.HOME ?? "/";
const PROFILE = Bun.env.KIMI_PROFILE ?? "";

if (Bun.argv.includes("--help")) {
  console.log("Sets up the kimi-toolchain CLI and scaffolds the project with kimi-fix.");
  console.log("");
  console.log("Usage:");
  console.log("  bun run scripts/postinstall.ts");
  console.log("  bun run scripts/postinstall.ts --with-secrets");
  console.log('  bun run scripts/postinstall.ts --with-secrets --secrets "github-token,npm-token"');
  console.log("");
  console.log("Options:");
  console.log("  --with-secrets  Generate a root secrets/ registry");
  console.log("  --service       Service app name (default: derived from destination directory)");
  console.log("  --domain        Service domain prefix (default: com.kimi)");
  console.log(
    "  --secrets       Comma-separated secret names when --with-secrets is set (default: api-key,db-url)"
  );
  process.exit(0);
}

const installProc = Bun.spawn(
  ["bun", "install", "-g", "github:brendadeeznuts1111/kimi-toolchain"],
  {
    cwd: DEST,
    env: { ...Bun.env, HOME },
    stdout: "inherit",
    stderr: "inherit",
  }
);
await installProc.exited;

const kimiFix = Bun.which("kimi-fix");
if (!kimiFix) {
  console.error("kimi-fix not found in PATH after global install.");
  process.exit(1);
}

const fixArgs = ["."];
if (PROFILE) fixArgs.push("--profile", PROFILE);
const fixProc = Bun.spawn([kimiFix, ...fixArgs], {
  cwd: DEST,
  env: {
    ...Bun.env,
    HOME,
    PATH: Bun.env.KIMI_SCAFFOLD_HOME
      ? `${Bun.env.KIMI_SCAFFOLD_HOME}/.bun/bin:${Bun.env.PATH ?? ""}`
      : Bun.env.PATH,
  },
  stdout: "inherit",
  stderr: "inherit",
});
await fixProc.exited;

// ── Optional root secrets/ registry ──
if (values["with-secrets"]) {
  const domain = values.domain as string;
  const service = (values.service ?? deriveServiceName()) as string;
  const fullService = `${domain}.${service}`;
  const secretNames = (values.secrets as string).split(",").map((s) => s.trim());

  const secretsDir = join(DEST, "secrets");
  await Bun.spawn(["mkdir", "-p", secretsDir]).exited;

  const bt = "`";

  const registry = `// AUTO-GENERATED by postinstall.ts -- do not hand-edit
export const SERVICE_ID = "${fullService}" as const;

export const SECRET_NAMES = [
${secretNames.map((s) => `  "${s}",`).join("\n")}
] as const;

export type SecretName = (typeof SECRET_NAMES)[number];

export const SERVICE_META = {
  id: SERVICE_ID,
  domain: "${domain}",
  app: "${service}",
  secretCount: ${secretNames.length},
  createdAt: "${new Date().toISOString()}",
} as const;
`;
  await Bun.write(join(secretsDir, "_registry.ts"), registry);

  const access = `import { SERVICE_ID, SECRET_NAMES, type SecretName } from "./_registry.ts";
import { enforceIsolation } from "./isolation.ts";

function envKey(key: string): string {
  return key.toUpperCase().replace(/-/g, "_").replace(/\\./g, "_");
}

export const secrets = {
  service: SERVICE_ID,

  async get<N extends SecretName>(name: N): Promise<string | undefined> {
    const key = ${bt}\${SERVICE_ID}/\${name}${bt};
    enforceIsolation(SERVICE_ID, key);
    const fromBun = await Bun.secrets?.get({ service: SERVICE_ID, name });
    return fromBun ?? Bun.env[envKey(key)];
  },

  async require<N extends SecretName>(name: N): Promise<string> {
    const val = await this.get(name);
    if (!val) throw new Error(${bt}Missing secret: \${SERVICE_ID}/\${name}${bt});
    return val;
  },

  async resolve(): Promise<Record<SecretName, boolean>> {
    const resolved = {} as Record<SecretName, boolean>;
    for (const name of SECRET_NAMES) resolved[name] = !!(await this.get(name));
    return resolved;
  },

  async dryRun(): Promise<void> {
    console.table(
      await Promise.all(
        SECRET_NAMES.map(async (n) => ({
          service: SERVICE_ID,
          name: n,
          key: ${bt}\${SERVICE_ID}/\${n}${bt},
          status: (await this.get(n)) ? "✅" : "❌",
        }))
      ),
      ["service", "name", "key", "status"]
    );
  },
};
`;
  await Bun.write(join(secretsDir, "access.ts"), access);

  const isolation = `export class SecretIsolationError extends Error {
  readonly code = "SECRET_ISOLATION_VIOLATION";
  constructor(readonly caller: string, readonly key: string) {
    super(${bt}Isolation breach: \${caller} attempted to access \${key}${bt});
  }
}

export function enforceIsolation(caller: string, key: string): void {
  const prefix = ${bt}\${caller}/${bt};
  if (!key.startsWith(prefix)) {
    throw new SecretIsolationError(caller, key);
  }
}
`;
  await Bun.write(join(secretsDir, "isolation.ts"), isolation);

  const legacy = `import { secrets } from "./access.ts";

export async function resolveDevSecrets(): Promise<Record<string, boolean>> {
  return secrets.resolve();
}
`;
  await Bun.write(join(secretsDir, "legacy.ts"), legacy);

  const index = `export { SERVICE_ID, SECRET_NAMES, SERVICE_META, type SecretName } from "./_registry.ts";
export { secrets } from "./access.ts";
export { enforceIsolation, SecretIsolationError } from "./isolation.ts";
export { resolveDevSecrets } from "./legacy.ts";
`;
  await Bun.write(join(secretsDir, "index.ts"), index);

  console.log(
    `✅ Root secrets/ registry generated for ${fullService} with ${secretNames.length} secrets`
  );
}
