#!/usr/bin/env bun
/**
 * template-bootstrap: generates secrets slice then delegates to kimi-fix (pre-registry spawn).
 */
import { parseArgs } from "util";
import { join } from "path";

const DEST = process.cwd();
const STATE_FILE = join(DEST, ".herdr-scaffold-state.json");

const { values } = parseArgs({
  args: Bun.argv,
  options: {
    service: { type: "string" },
    domain: { type: "string", default: "com.herdr" },
    secrets: { type: "string", default: "api-key,db-url" },
    force: { type: "boolean", default: false },
  },
  strict: false,
  allowPositionals: true,
});

if (!values.force && (await Bun.file(STATE_FILE).exists())) {
  const state = await Bun.file(STATE_FILE).json();
  if (state.completed) {
    console.log(`⏭️  Scaffold already completed at ${state.completedAt}. Skipping.`);
    console.log(`   Use --force to regenerate.`);
    process.exit(0);
  }
}

const domain = values.domain as string;
const service = (values.service ?? (await promptService())) as string;
const fullService = `${domain}.${service}`;
const secrets = (values.secrets as string).split(",").map((s) => s.trim());

const secretsDir = join(DEST, "src/lib/secrets");

await Bun.write(
  join(secretsDir, "_registry.ts"),
  `// AUTO-GENERATED by postinstall.ts — do not hand-edit
export const SERVICE_ID = "${fullService}" as const;

export const SECRET_NAMES = [
${secrets.map((s) => `  "${s}",`).join("\n")}
] as const;

export type SecretName = (typeof SECRET_NAMES)[number];

export const SERVICE_META = {
  id: SERVICE_ID,
  domain: "${domain}",
  app: "${service}",
  secretCount: ${secrets.length},
  createdAt: "${new Date().toISOString()}",
} as const;
`
);

await Bun.write(
  join(secretsDir, "isolation.ts"),
  `export class SecretIsolationError extends Error {
  readonly code = "SECRET_ISOLATION_VIOLATION";
  constructor(readonly caller: string, readonly key: string) {
    super(\`Isolation breach: \${caller} attempted to access \${key}\`);
  }
}

export function enforceIsolation(caller: string, key: string): void {
  const prefix = \`\${caller}/\`;
  if (!key.startsWith(prefix)) {
    throw new SecretIsolationError(caller, key);
  }
}
`
);

await Bun.write(
  join(secretsDir, "access.ts"),
  `import { SERVICE_ID, SECRET_NAMES, type SecretName } from "./_registry.ts";
import { enforceIsolation } from "./isolation.ts";

async function getSecret(service: string, name: string): Promise<string | undefined> {
  let fromSecrets: string | undefined;
  try {
    const val = await (Bun.secrets as any)?.get?.({ service, name });
    fromSecrets = val ?? undefined;
  } catch {
    try {
      fromSecrets = (Bun.secrets as any)?.[\`\${service}/\${name}\`] as string | undefined;
    } catch {}
  }
  const envKey = \`\${service}/\${name}\`.toUpperCase().replace(/-/g, "_").replace(/\\./g, "_");
  const fromEnv = Bun.env[envKey];
  return fromSecrets ?? fromEnv;
}

export const secrets = {
  service: SERVICE_ID,

  async get<N extends SecretName>(name: N): Promise<string | undefined> {
    const key = \`\${SERVICE_ID}/\${name}\`;
    enforceIsolation(SERVICE_ID, key);
    return getSecret(SERVICE_ID, name);
  },

  async require<N extends SecretName>(name: N): Promise<string> {
    const val = await this.get(name);
    if (!val) {
      throw new Error(
        \`Missing secret: \${SERVICE_ID}/\${name}\\n\` +
        \`  Store:   bun secrets set \${SERVICE_ID}/\${name} <value>\\n\` +
        \`  Or env:  export \${SERVICE_ID.replace(/\\./g, "_").toUpperCase()}_\${name.toUpperCase().replace(/-/g, "_")}=<value>\`
      );
    }
    return val;
  },

  async resolve(): Promise<Record<SecretName, boolean>> {
    const resolved = {} as Record<SecretName, boolean>;
    for (const name of SECRET_NAMES) resolved[name] = !!(await this.get(name));
    return resolved;
  },

  async dryRun(): Promise<void> {
    const rows = await Promise.all(
      SECRET_NAMES.map(async (n) => ({
        service: SERVICE_ID,
        name: n,
        key: \`\${SERVICE_ID}/\${n}\`,
        status: (await this.get(n)) ? "✅" : "❌",
      }))
    );
    console.table(rows, ["service", "name", "key", "status"]);
  },
};
`
);

await Bun.write(
  join(secretsDir, "legacy.ts"),
  `import { secrets } from "./access.ts";

export async function resolveDevSecrets(): Promise<Record<string, boolean>> {
  return secrets.resolve();
}
`
);

await Bun.write(
  join(secretsDir, "index.ts"),
  `export { SERVICE_ID, SECRET_NAMES, SERVICE_META, type SecretName } from "./_registry.ts";
export { secrets } from "./access.ts";
export { enforceIsolation, SecretIsolationError } from "./isolation.ts";
export { resolveDevSecrets } from "./legacy.ts";
`
);

const testDir = join(DEST, "test");
await Bun.write(
  join(testDir, "secrets.unit.test.ts"),
  `import { describe, test, expect } from "bun:test";
import { secrets, SERVICE_ID, SECRET_NAMES, SecretIsolationError, enforceIsolation } from "../src/lib/secrets/index.ts";

describe("secret isolation", () => {
  test("SERVICE_ID matches reverse-domain pattern", () => {
    expect(SERVICE_ID).toMatch(/^com\\.herdr\\.[a-z-]+$/);
  });

  test("SECRET_NAMES is non-empty", () => {
    expect(SECRET_NAMES.length).toBeGreaterThan(0);
  });

  test("enforceIsolation rejects cross-service keys", () => {
    expect(() => {
      enforceIsolation("com.herdr.other", \`\${SERVICE_ID}/api-key\`);
    }).toThrow(SecretIsolationError);
  });

  test("resolve() returns record for all declared secrets", async () => {
    const resolved = await secrets.resolve();
    for (const name of SECRET_NAMES) {
      expect(resolved).toHaveProperty(name);
    }
  });

  test("dryRun() prints without error", async () => {
    await secrets.dryRun();
  });
});
`
);

const dxPath = join(DEST, "dx.config.toml");
if (await Bun.file(dxPath).exists()) {
  const raw = await Bun.file(dxPath).text();
  await Bun.write(dxPath, raw.replace(/{{SERVICE}}/g, fullService).replace(/{{APP}}/g, service));
}

await Bun.write(
  STATE_FILE,
  JSON.stringify(
    {
      completed: true,
      completedAt: new Date().toISOString(),
      service: fullService,
      secrets,
    },
    null,
    2
  )
);

const kimiFix = Bun.which("kimi-fix");
if (kimiFix) {
  console.log("🔧 Delegating to kimi-fix...");
  const proc = Bun.spawn([kimiFix, ".", "--profile", "toolchain"], {
    cwd: DEST,
    stdout: "inherit",
    stderr: "inherit",
  });
  const timeout = Bun.sleep(30_000).then(() => {
    proc.kill("SIGTERM");
    return false as const;
  });
  const exited = proc.exited.then(() => true as const);
  const finishedFirst = await Promise.race([timeout, exited]);
  if (!finishedFirst) {
    console.warn(
      "⚠️  kimi-fix timed out after 30s; run manually if needed: kimi-fix . --profile toolchain"
    );
  }
} else {
  console.warn("⚠️  kimi-fix not found in PATH. Run manually: kimi-fix . --profile toolchain");
}

console.log(`✅ ${fullService} scaffolded with ${secrets.length} secrets`);
console.log(`   Run: bun run src/lib/secrets/access.ts (dry-run)`);

async function promptService(): Promise<string> {
  const base = DEST.split("/").pop() ?? "herdr-service";
  const sanitized = base
    .replace(/[^a-zA-Z0-9_-]/g, "-")
    .replace(/^-+|-+$/g, "")
    .toLowerCase();
  const fallback = sanitized || "herdr-service";
  if (!process.stdin.isTTY) {
    console.log(`Service name not provided; using default: ${fallback}`);
    return fallback;
  }
  console.write(`Service name (default: ${fallback}): `);
  for await (const line of console) {
    const trimmed = line.trim();
    return trimmed || fallback;
  }
  return fallback;
}
