#!/usr/bin/env bun
/**
 * postinstall.ts — herdr-service-template setup
 *
 * Reads the --secrets flag, generates _registry.ts, runs generate-resolvers.ts,
 * and appends the service to the root UNIFIED.md secrets matrix.
 *
 * Usage (invoked by bun create postinstall):
 *   bun run scripts/postinstall.ts --secrets jwt-secret,csrf-secret,api-key
 *   bun run scripts/postinstall.ts --service com.herdr.my-service --secrets jwt-secret,csrf-secret
 *
 * If --secrets is omitted, defaults to a minimal set: jwt-secret,csrf-secret.
 * If --service is omitted, derives from package.json name.
 */

import { join, resolve } from "path";
import { existsSync, readFileSync } from "fs";

interface PostinstallArgs {
  secrets: string[];
  service: string;
  projectDir: string;
}

function parseArgs(): PostinstallArgs {
  const args = process.argv.slice(2);
  const projectDir = process.cwd();

  let secrets: string[] = ["jwt-secret", "csrf-secret"];
  let service = "";

  const secretsIdx = args.indexOf("--secrets");
  if (secretsIdx !== -1 && args[secretsIdx + 1]) {
    secrets = args[secretsIdx + 1].split(",").map((s) => s.trim()).filter(Boolean);
  }

  const serviceIdx = args.indexOf("--service");
  if (serviceIdx !== -1 && args[serviceIdx + 1]) {
    service = args[serviceIdx + 1];
  }

  if (!service) {
    const pkgPath = join(projectDir, "package.json");
    if (existsSync(pkgPath)) {
      const pkg = JSON.parse(readFileSync(pkgPath, "utf-8"));
      const name = pkg.name || "my-service";
      service = name.startsWith("com.") ? name : `com.herdr.${name.replace(/[^a-z0-9-]/gi, "")}`;
    } else {
      service = "com.herdr.my-service";
    }
  }

  return { secrets, service, projectDir };
}

function generateRegistry(serviceId: string, secretNames: string[]): string {
  return `/**
 * _registry.ts — Service identity and secret declarations.
 *
 * Auto-generated by herdr-service-template postinstall.
 * DO NOT EDIT MANUALLY — re-run: bun run scripts/postinstall.ts --secrets ...
 */

export const SERVICE_ID = "${serviceId}" as const;

export const SECRET_NAMES = [${secretNames.map((s) => `"${s}"`).join(", ")}] as const;

export type SecretName = typeof SECRET_NAMES[number];
`;
}

function appendToUnifiedMd(projectDir: string, serviceId: string, secretNames: string[]): void {
  const unifiedPath = join(projectDir, "UNIFIED.md");
  if (!existsSync(unifiedPath)) {
    console.log("  ℹ UNIFIED.md not found — skipping matrix append");
    return;
  }

  const content = readFileSync(unifiedPath, "utf-8");
  const marker = "<!-- SECRETS-MATRIX -->";
  const alreadyPresent = content.includes(`| \`${serviceId}\``);

  if (alreadyPresent) {
    console.log(`  ℹ ${serviceId} already in UNIFIED.md matrix — skipping`);
    return;
  }

  const secretsStr = secretNames.join(", ");
  const row = `| \`${serviceId}\` | ${secretsStr} |`;

  if (content.includes(marker)) {
    const updated = content.replace(marker, `${marker}\n${row}`);
    Bun.write(unifiedPath, updated);
  } else {
    const section = [
      "",
      "## Secrets matrix",
      "",
      "| Service | Secrets |",
      "| ------- | ------- |",
      row,
      marker,
      "",
    ].join("\n");
    Bun.write(unifiedPath, content.trimEnd() + "\n" + section);
  }

  console.log(`  ✓ Appended ${serviceId} to UNIFIED.md secrets matrix`);
}

async function main(): Promise<void> {
  const { secrets, service, projectDir } = parseArgs();

  console.log("🔧 Setting up herdr-service-template...");
  console.log(`  Service: ${service}`);
  console.log(`  Secrets: ${secrets.join(", ")}`);

  const registryDir = join(projectDir, "src", "lib");
  const registryPath = join(registryDir, "_registry.ts");

  if (!existsSync(registryDir)) {
    await Bun.write(join(registryDir, ".gitkeep"), "");
  }

  const registryContent = generateRegistry(service, secrets);
  await Bun.write(registryPath, registryContent);
  console.log(`  ✓ Wrote src/lib/_registry.ts`);

  const resolverScript = join(projectDir, "scripts", "generate-resolvers.ts");
  if (existsSync(resolverScript)) {
    const proc = Bun.spawn(["bun", "run", resolverScript], {
      cwd: projectDir,
      stdout: "pipe",
      stderr: "pipe",
    });
    const exitCode = await proc.exited;
    if (exitCode !== 0) {
      const stderr = await new Response(proc.stderr).text();
      console.warn(`  ⚠ generate-resolvers.ts exited ${exitCode}: ${stderr.trim()}`);
    } else {
      const stdout = await new Response(proc.stdout).text();
      console.log(`  ✓ ${stdout.trim()}`);
    }
  } else {
    console.warn("  ⚠ scripts/generate-resolvers.ts not found — skipping resolver generation");
  }

  appendToUnifiedMd(projectDir, service, secrets);

  console.log("✅ herdr-service-template ready");
  console.log(`   Service ID: ${service}`);
  console.log(`   Secrets:    ${secrets.length} registered`);
  console.log(`   Resolvers:  bun run resolvers:generate`);
  console.log(`   Start:      bun run dev`);
}

main().catch((err: Error) => {
  console.error("postinstall failed:", err.message);
  process.exit(1);
});
