#!/usr/bin/env bun
/**
 * build-theme.ts — Build-time CSS theme generator using Bun.color macro.
 *
 * Reads color tokens from `src/lib/theme-tokens.ts` and generates a CSS
 * file with custom properties (CSS variables) for each token. The color
 * values are converted to the most compact CSS representation at build
 * time using `Bun.color(input, "css")`. For client-side code that needs
 * compile-time color conversion, use the macro import:
 *   `import { color } from "bun" with { type: "macro" };`
 *
 * Usage:
 *   bun run scripts/build-theme.ts [--outdir dist] [--format css|hex|HEX]
 *
 * Output:
 *   dist/theme.css — CSS file with :root { --token: value; } declarations
 *   dist/theme.json — JSON manifest of all tokens (for JS consumers)
 */

import { allTokens, cssVarName, type ThemeToken } from "../src/lib/theme-tokens.ts";

// ── CLI Args ─────────────────────────────────────────────────────────

interface BuildThemeArgs {
  outdir: string;
  format: "css" | "hex" | "HEX";
}

function parseArgs(argv: string[]): BuildThemeArgs {
  const args = argv.slice(2);
  let outdir = "dist";
  let format: "css" | "hex" | "HEX" = "css";

  for (let i = 0; i < args.length; i++) {
    if (args[i] === "--outdir" && args[i + 1]) {
      outdir = args[i + 1];
      i++;
    } else if (args[i] === "--format" && args[i + 1]) {
      const f = args[i + 1];
      if (f === "css" || f === "hex" || f === "HEX") {
        format = f;
      }
      i++;
    }
  }

  return { outdir, format };
}

// ── CSS Generation ───────────────────────────────────────────────────

/**
 * Convert a hex color to the target format using Bun.color.
 * When used with the macro import, this is evaluated at build time.
 */
function convertColor(hex: string, format: "css" | "hex" | "HEX"): string {
  return Bun.color(hex, format) ?? hex;
}

/** Generate the CSS :root block with all custom properties. */
function generateCss(tokens: ThemeToken[], format: "css" | "hex" | "HEX"): string {
  const lines = tokens.map((t) => {
    const cssValue = convertColor(t.value, format);
    const varName = cssVarName(t.name);
    return `  ${varName}: ${cssValue};`;
  });

  return `/* Generated by build-theme.ts — do not edit manually. */
/* Format: ${format} | Tokens: ${tokens.length} */
:root {
${lines.join("\n")}
}`;
}

/** Generate a JSON manifest of all tokens. */
function generateManifest(tokens: ThemeToken[], format: "css" | "hex" | "HEX"): string {
  const manifest: Record<string, { value: string; css: string; category: string }> = {};
  for (const t of tokens) {
    manifest[t.name] = {
      value: t.value,
      css: convertColor(t.value, format),
      category: t.category,
    };
  }
  return JSON.stringify(manifest, null, 2);
}

// ── Main ─────────────────────────────────────────────────────────────

async function main(): Promise<number> {
  const { outdir, format } = parseArgs(Bun.argv);
  const tokens = allTokens();

  // Ensure output directory exists
  const outdirAbs = `${Bun.cwd}/${outdir}`;
  await Bun.write(`${outdirAbs}/.gitkeep`, "");

  // Generate and write CSS
  const css = generateCss(tokens, format);
  await Bun.write(`${outdirAbs}/theme.css`, css);

  // Generate and write JSON manifest
  const manifest = generateManifest(tokens, format);
  await Bun.write(`${outdirAbs}/theme.json`, manifest);

  console.log(`✓ Generated ${tokens.length} tokens → ${outdir}/theme.css (${format})`);
  console.log(`✓ Manifest → ${outdir}/theme.json`);

  return 0;
}

// Run if executed directly
if (import.meta.main) {
  const exit = await main();
  process.exit(exit);
}

// Export for testing
export { generateCss, generateManifest, convertColor, parseArgs };
