#compdef bun
# zsh completion for bun
# Generated by scripts/generate-cli-completions.ts — do not edit manually

_bun_commands() {
  local -a commands
  commands=(
    'run:Flags:'
    'test:Run all matching test files and print the results to stdout'
    'x:Execute an npm package executable (CLI), automatically installing into a global shared cache if not installed in node_modules.'
    'repl:Flags:'
    'exec:Execute a shell script directly from Bun.'
    'install:Install the dependencies listed in package.json.'
    'add:Add a new dependency to package.json and install it.'
    'remove:Remove a package from package.json and uninstall from node_modules.'
    'update:Update dependencies to their most recent versions within the version range in package.json.'
    'audit:Check installed packages for vulnerabilities.'
    'outdated:bun outdated v1.4.0-canary.1 (452139e36)'
    'link:Register a local directory as a "linkable" package, or link a "linkable" package to the current project.'
    'unlink:Unregister the current directory as a "linkable" package.'
    'publish:bun publish v1.4.0-canary.1 (452139e36)'
    'patch:Prepare a package for patching, or generate and save a patch.'
    'pm:Run package manager utilities.'
    'info:View package metadata from the registry.'
    'why:Explain why a package is installed'
    'build:Transpile and bundle one or more files.'
    'init:Initialize a Bun project in the current directory.'
    'create:bun create <MyReactComponent.(jsx|tsx)>'
    'upgrade:Upgrade Bun'
    'feedback:bun feedback'
  )
  _describe -t commands 'bun command' commands
}

_bun_global_flags() {
  local -a flags
  flags=(
    '( --silent)--silent[Don'\''t print the script command]'
    '( --elide-lines)--elide-lines[Number of lines of script output shown when using --filter (default: 10). Set to 0 to show all lines.]'
    '( -v --version) -v--version[Print version and exit]'
    '( --revision)--revision[Print version with revision and exit]'
    '( -F --filter) -F--filter[Run a script in all workspace packages matching the pattern]'
    '( -b --bun) -b--bun[Force a script or package to use Bun'\''s runtime instead of Node.js (via symlinking node)]'
    '( --no-orphans)--no-orphans[Exit when the parent process dies, and on exit SIGKILL every descendant. Linux/macOS only.]'
    '( --shell)--shell[Control the shell used for package.json scripts. Supports either '\''bun'\'' or '\''system'\'']'
    '( --workspaces)--workspaces[Run a script in all workspace packages (from the "workspaces" field in package.json)]'
    '( --parallel)--parallel[Run multiple scripts concurrently with Foreman-style output]'
    '( --sequential)--sequential[Run multiple scripts sequentially with Foreman-style output]'
    '( --no-exit-on-error)--no-exit-on-error[Continue running other scripts when one fails (with --parallel/--sequential)]'
    '( --watch)--watch[Automatically restart the process on file change]'
    '( --hot)--hot[Enable auto reload in the Bun runtime, test runner, or bundler]'
    '( --no-clear-screen)--no-clear-screen[Disable clearing the terminal screen on reload when --hot or --watch is enabled]'
    '( --smol)--smol[Use less memory, but run garbage collection more often]'
    '( -r --preload) -r--preload[Import a module before other modules are loaded]'
    '( --require)--require[Alias of --preload, for Node.js compatibility]'
    '( --import)--import[Alias of --preload, for Node.js compatibility]'
    '( --inspect)--inspect[Activate Bun'\''s debugger]'
    '( --inspect-wait)--inspect-wait[Activate Bun'\''s debugger, wait for a connection before executing]'
    '( --inspect-brk)--inspect-brk[Activate Bun'\''s debugger, set breakpoint on first line of code and wait]'
    '( --cpu-prof)--cpu-prof[Start CPU profiler and write profile to disk on exit]'
    '( --cpu-prof-name)--cpu-prof-name[Specify the name of the CPU profile file]'
    '( --cpu-prof-dir)--cpu-prof-dir[Specify the directory where the CPU profile will be saved]'
    '( --cpu-prof-md)--cpu-prof-md[Output CPU profile in markdown format (grep-friendly, designed for LLM analysis)]'
    '( --cpu-prof-interval)--cpu-prof-interval[Specify the sampling interval in microseconds for CPU profiling (default: 1000)]'
    '( --heap-prof)--heap-prof[Generate V8 heap snapshot on exit (.heapsnapshot)]'
    '( --heap-prof-name)--heap-prof-name[Specify the name of the heap profile file]'
    '( --heap-prof-dir)--heap-prof-dir[Specify the directory where the heap profile will be saved]'
    '( --heap-prof-md)--heap-prof-md[Generate markdown heap profile on exit (for CLI analysis)]'
    '( --if-present)--if-present[Exit without an error if the entrypoint does not exist]'
    '( --no-install)--no-install[Disable auto install in the Bun runtime]'
    '( --install)--install[Configure auto-install behavior. One of "auto" (default, auto-installs when no node_modules), "fallback" (missing packages only), "force" (always).]'
    '( -i --i) -i--i[Auto-install dependencies during execution. Equivalent to --install=fallback.]'
    '( -e --eval) -e--eval[Evaluate argument as a script]'
    '( -p --print) -p--print[Evaluate argument as a script and print the result]'
    '( --prefer-offline)--prefer-offline[Skip staleness checks for packages in the Bun runtime and resolve from disk]'
    '( --prefer-latest)--prefer-latest[Use the latest matching versions of packages in the Bun runtime, always checking npm]'
    '( --port)--port[Set the default port for Bun.serve]'
    '( --conditions)--conditions[Pass custom conditions to resolve]'
    '( --fetch-preconnect)--fetch-preconnect[Preconnect to a URL while code is loading]'
    '( --experimental-http2-fetch)--experimental-http2-fetch[Offer h2 in fetch() TLS ALPN. Same as BUN_FEATURE_FLAG_EXPERIMENTAL_HTTP2_CLIENT=1]'
    '( --experimental-http3-fetch)--experimental-http3-fetch[Honor Alt-Svc: h3 in fetch() and upgrade to HTTP/3. Same as BUN_FEATURE_FLAG_EXPERIMENTAL_HTTP3_CLIENT=1]'
    '( --max-http-header-size)--max-http-header-size[Set the maximum size of HTTP headers in bytes. Default is 16KiB]'
    '( --dns-result-order)--dns-result-order[Set the default order of DNS lookup results. Valid orders: verbatim (default), ipv4first, ipv6first]'
    '( --experimental-stream-iter)--experimental-stream-iter[Enable the experimental stream/iter API (node:stream/iter, node:zlib/iter).]'
    '( --expose-gc)--expose-gc[Expose gc() on the global object. Has no effect on Bun.gc().]'
    '( --no-deprecation)--no-deprecation[Suppress all reporting of the custom deprecation.]'
    '( --throw-deprecation)--throw-deprecation[Determine whether or not deprecation warnings result in errors.]'
    '( --title)--title[Set the process title]'
    '( --zero-fill-buffers)--zero-fill-buffers[Boolean to force Buffer.allocUnsafe(size) to be zero-filled.]'
    '( --use-system-ca)--use-system-ca[Use the system'\''s trusted certificate authorities]'
    '( --use-openssl-ca)--use-openssl-ca[Use OpenSSL'\''s default CA store]'
    '( --use-bundled-ca)--use-bundled-ca[Use bundled CA store]'
    '( --redis-preconnect)--redis-preconnect[Preconnect to $REDIS_URL at startup]'
    '( --sql-preconnect)--sql-preconnect[Preconnect to PostgreSQL at startup]'
    '( --no-addons)--no-addons[Throw an error if process.dlopen is called, and disable export condition "node-addons"]'
    '( --unhandled-rejections)--unhandled-rejections[One of "strict", "throw", "warn", "none", or "warn-with-error-code"]'
    '( --console-depth)--console-depth[Set the default depth for console.log object inspection (default: 2)]'
    '( --user-agent)--user-agent[Set the default User-Agent header for HTTP requests]'
    '( --cron-title)--cron-title[Title for cron execution mode]'
    '( --cron-period)--cron-period[Cron period for cron execution mode]'
    '( --main-fields)--main-fields[Main fields to lookup in package.json. Defaults to --target dependent]'
    '( --preserve-symlinks)--preserve-symlinks[Preserve symlinks when resolving files]'
    '( --preserve-symlinks-main)--preserve-symlinks-main[Preserve symlinks when resolving the main entry point]'
    '( --extension-order)--extension-order[Defaults to: .tsx,.ts,.jsx,.js,.json]'
    '( --tsconfig-override)--tsconfig-override[Specify custom tsconfig.json. Default $cwd/tsconfig.json]'
    '( -d --define) -d--define[Substitute K:V while parsing, e.g. --define process.env.NODE_ENV:"development". Values are parsed as JSON.]'
    '( --drop)--drop[Remove function calls, e.g. --drop=console removes all console.* calls.]'
    '( --feature)--feature[Enable a feature flag for dead-code elimination, e.g. --feature=SUPER_SECRET]'
    '( -l --loader) -l--loader[Parse files with .ext:loader, e.g. --loader .js:jsx. Valid loaders: js, jsx, ts, tsx, json, toml, text, file, wasm, napi]'
    '( --no-macros)--no-macros[Disable macros from being executed in the bundler, transpiler and runtime]'
    '( --jsx-factory)--jsx-factory[Changes the function called when compiling JSX elements using the classic JSX runtime]'
    '( --jsx-fragment)--jsx-fragment[Changes the function called when compiling JSX fragments]'
    '( --jsx-import-source)--jsx-import-source[Declares the module specifier to be used for importing the jsx and jsxs factory functions. Default: "react"]'
    '( --jsx-runtime)--jsx-runtime["automatic" (default) or "classic"]'
    '( --jsx-side-effects)--jsx-side-effects[Treat JSX elements as having side effects (disable pure annotations)]'
    '( --ignore-dce-annotations)--ignore-dce-annotations[Ignore tree-shaking annotations such as @__PURE__]'
    '( --env-file)--env-file[Load environment variables from the specified file(s)]'
    '( --no-env-file)--no-env-file[Disable automatic loading of .env files]'
    '( --cwd)--cwd[Absolute path to resolve files & entry points from. This just changes the process'\'' cwd.]'
    '( -c --config) -c--config[Specify path to Bun config file. Default $cwd/bunfig.toml]'
    '( -h --help) -h--help[Display this menu and exit]'
  )
  _arguments -s -S $flags
}

_bun_scripts() {
  local -a scripts
  scripts=(${(f)"$(bun getcompletes s 2>/dev/null)"})
  _describe -t scripts 'package script' scripts
}

_bun_installed_packages() {
  local -a packages
  packages=(${(f)"$(bun getcompletes a "$words[$CURRENT]" 2>/dev/null)"})
  _describe -t packages 'installed package' packages
}

_bun_files() {
  _files -g '*.(js|ts|jsx|tsx|mjs|cjs)'
}

_bun() {
  local curcontext="$curcontext" state line
  typeset -A opt_args

  _arguments -C \
    '1: :_bun_commands' \
    '*:: :->subcmd'

  case "$state" in
    subcmd)
      case "$line[1]" in
        run)
          _arguments -s -S \
            # no flags
          _alternative \
            'scripts:package script:_bun_scripts' \
            'files:javascript file:_bun_files'
          ;;
        test)
          _arguments -s -S \
            '( --no-orphans)--no-orphans[Exit when the parent process dies, and on exit SIGKILL every descendant. Linux/macOS only.]' \
            '( --timeout)--timeout[Set the per-test timeout in milliseconds, default is 5000.]' \
            '( -u --update-snapshots) -u--update-snapshots[Update snapshot files]' \
            '( --rerun-each)--rerun-each[Re-run each test file  times, helps catch certain bugs]' \
            '( --retry)--retry[Default retry count for all tests, overridden by per-test { retry: N }]' \
            '( --todo)--todo[Include tests that are marked with "test.todo()"]' \
            '( --only)--only[Run only tests that are marked with "test.only()" or "describe.only()"]' \
            '( --pass-with-no-tests)--pass-with-no-tests[Exit with code 0 when no tests are found]' \
            '( --concurrent)--concurrent[Treat all tests as `test.concurrent()` tests]' \
            '( --randomize)--randomize[Run tests in random order]' \
            '( --seed)--seed[Set the random seed for test randomization]' \
            '( --coverage)--coverage[Generate a coverage profile]' \
            '( --coverage-reporter)--coverage-reporter[Report coverage in '\''text'\'' and/or '\''lcov'\''. Defaults to '\''text'\''.]' \
            '( --coverage-dir)--coverage-dir[Directory for coverage files. Defaults to '\''coverage'\''.]' \
            '( --bail)--bail[Exit the test suite after  failures. If you do not specify a number, it defaults to 1.]' \
            '( -t --test-name-pattern) -t--test-name-pattern[Run only tests with a name that matches the given regex.]' \
            '( --reporter)--reporter[Test output reporter format. Available: '\''junit'\'' (requires --reporter-outfile), '\''dots'\''. Default: console output.]' \
            '( --reporter-outfile)--reporter-outfile[Output file path for the reporter format (required with --reporter).]' \
            '( --dots)--dots[Enable dots reporter. Shorthand for --reporter=dots.]' \
            '( --only-failures)--only-failures[Only display test failures, hiding passing tests.]' \
            '( --max-concurrency)--max-concurrency[Maximum number of concurrent tests to execute at once. Default is 20.]' \
            '( --path-ignore-patterns)--path-ignore-patterns[Glob patterns for test file paths to ignore.]' \
            '( --changed)--changed[Only run test files affected by changed files according to git. Optionally pass a commit or branch to compare against.]' \
            '( --isolate)--isolate[Run each test file in a fresh global object. Leaked handles from one file cannot affect another.]' \
            '( --parallel)--parallel[Run test files in parallel using N worker processes. Implies --isolate. Defaults to CPU core count.]' \
            '( --parallel-delay)--parallel-delay[Milliseconds the first --parallel worker must be busy before spawning the rest. 0 spawns all immediately. Default 5.]' \
            '( --test-worker)--test-worker[(internal) Run as a --parallel worker, receiving files over IPC.]' \
            '( --shard)--shard[Run a subset of test files, e.g. '\''--shard=1/3'\'' runs the first of three shards. Useful for splitting tests across multiple CI jobs.]'
          _bun_files
          ;;
        x|bunx)
          _arguments -s -S \
            '( --bun)--bun[Force the command to run with Bun instead of Node.js]' \
            '( -p --package) -p--package[<package>    Specify package to install when binary name differs from package name]' \
            '( --no-install)--no-install[Skip installation if package is not already installed]' \
            '( --verbose)--verbose[Enable verbose output during installation]' \
            '( --silent)--silent[Suppress output during installation]'
          ;;
        repl)
          _arguments -s -S \
            # no flags
          ;;
        exec)
          _arguments -s -S \
            # no flags
          ;;
        install|i)
          _arguments -s -S \
            '( -c --config) -c--config[Specify path to config file (bunfig.toml)]' \
            '( -y --yarn) -y--yarn[Write a yarn.lock file (yarn v1)]' \
            '( -p --production) -p--production[Don'\''t install devDependencies]' \
            '( --no-save)--no-save[Don'\''t update package.json or save a lockfile]' \
            '( --save)--save[Save to package.json (true by default)]' \
            '( --ca)--ca[Provide a Certificate Authority signing certificate]' \
            '( --cafile)--cafile[The same as `--ca`, but is a file path to the certificate]' \
            '( --dry-run)--dry-run[Perform a dry run without making changes]' \
            '( --frozen-lockfile)--frozen-lockfile[Disallow changes to lockfile]' \
            '( -f --force) -f--force[Always request the latest versions from the registry & reinstall all dependencies]' \
            '( --cache-dir)--cache-dir[Store & load cached data from a specific directory path]' \
            '( --no-cache)--no-cache[Ignore manifest cache entirely]' \
            '( --silent)--silent[Don'\''t log anything]' \
            '( --quiet)--quiet[Only show tarball name when packing]' \
            '( --verbose)--verbose[Excessively verbose logging]' \
            '( --no-progress)--no-progress[Disable the progress bar]' \
            '( --no-summary)--no-summary[Don'\''t print a summary]' \
            '( --no-verify)--no-verify[Skip verifying integrity of newly downloaded packages]' \
            '( --ignore-scripts)--ignore-scripts[Skip lifecycle scripts in the project'\''s package.json (dependency scripts are never run)]' \
            '( --trust)--trust[Add to trustedDependencies in the project'\''s package.json and install the package(s)]' \
            '( -g --global) -g--global[Install globally]' \
            '( --cwd)--cwd[Set a specific cwd]' \
            '( --backend)--backend[Platform-specific optimizations for installing dependencies. Possible values: "clonefile" (default), "hardlink", "symlink", "copyfile"]' \
            '( --registry)--registry[Use a specific registry by default, overriding .npmrc, bunfig.toml and environment variables]' \
            '( --concurrent-scripts)--concurrent-scripts[Maximum number of concurrent jobs for lifecycle scripts (default: 2x CPU cores)]' \
            '( --network-concurrency)--network-concurrency[Maximum number of concurrent network requests (default 48)]' \
            '( --save-text-lockfile)--save-text-lockfile[Save a text-based lockfile]' \
            '( --omit)--omit[Exclude '\''dev'\'', '\''optional'\'', or '\''peer'\'' dependencies from install]' \
            '( --lockfile-only)--lockfile-only[Generate a lockfile without installing dependencies]' \
            '( --linker)--linker[Linker strategy (one of "isolated" or "hoisted")]' \
            '( --minimum-release-age)--minimum-release-age[Only install packages published at least N seconds ago (security feature)]' \
            '( --cpu)--cpu[Override CPU architecture for optional dependencies (e.g., x64, arm64, * for all)]' \
            '( --os)--os[Override operating system for optional dependencies (e.g., linux, darwin, * for all)]' \
            '( -h --help) -h--help[Print this help menu]' \
            '( -d --dev) -d--dev[Add dependency to "devDependencies"]' \
            '( --optional)--optional[Add dependency to "optionalDependencies"]' \
            '( --peer)--peer[Add dependency to "peerDependencies"]' \
            '( -E --exact) -E--exact[Add the exact version instead of the ^range]' \
            '( --filter)--filter[Install packages for the matching workspaces]' \
            '( -a --analyze) -a--analyze[Analyze & install all dependencies of files passed as arguments recursively (using Bun'\''s bundler)]' \
            '( --only-missing)--only-missing[Only add dependencies to package.json if they are not already present]'
          ;;
        add|a)
          _arguments -s -S \
            '( -c --config) -c--config[Specify path to config file (bunfig.toml)]' \
            '( -y --yarn) -y--yarn[Write a yarn.lock file (yarn v1)]' \
            '( -p --production) -p--production[Don'\''t install devDependencies]' \
            '( --no-save)--no-save[Don'\''t update package.json or save a lockfile]' \
            '( --save)--save[Save to package.json (true by default)]' \
            '( --ca)--ca[Provide a Certificate Authority signing certificate]' \
            '( --cafile)--cafile[The same as `--ca`, but is a file path to the certificate]' \
            '( --dry-run)--dry-run[Perform a dry run without making changes]' \
            '( --frozen-lockfile)--frozen-lockfile[Disallow changes to lockfile]' \
            '( -f --force) -f--force[Always request the latest versions from the registry & reinstall all dependencies]' \
            '( --cache-dir)--cache-dir[Store & load cached data from a specific directory path]' \
            '( --no-cache)--no-cache[Ignore manifest cache entirely]' \
            '( --silent)--silent[Don'\''t log anything]' \
            '( --quiet)--quiet[Only show tarball name when packing]' \
            '( --verbose)--verbose[Excessively verbose logging]' \
            '( --no-progress)--no-progress[Disable the progress bar]' \
            '( --no-summary)--no-summary[Don'\''t print a summary]' \
            '( --no-verify)--no-verify[Skip verifying integrity of newly downloaded packages]' \
            '( --ignore-scripts)--ignore-scripts[Skip lifecycle scripts in the project'\''s package.json (dependency scripts are never run)]' \
            '( --trust)--trust[Add to trustedDependencies in the project'\''s package.json and install the package(s)]' \
            '( -g --global) -g--global[Install globally]' \
            '( --cwd)--cwd[Set a specific cwd]' \
            '( --backend)--backend[Platform-specific optimizations for installing dependencies. Possible values: "clonefile" (default), "hardlink", "symlink", "copyfile"]' \
            '( --registry)--registry[Use a specific registry by default, overriding .npmrc, bunfig.toml and environment variables]' \
            '( --concurrent-scripts)--concurrent-scripts[Maximum number of concurrent jobs for lifecycle scripts (default: 2x CPU cores)]' \
            '( --network-concurrency)--network-concurrency[Maximum number of concurrent network requests (default 48)]' \
            '( --save-text-lockfile)--save-text-lockfile[Save a text-based lockfile]' \
            '( --omit)--omit[Exclude '\''dev'\'', '\''optional'\'', or '\''peer'\'' dependencies from install]' \
            '( --lockfile-only)--lockfile-only[Generate a lockfile without installing dependencies]' \
            '( --linker)--linker[Linker strategy (one of "isolated" or "hoisted")]' \
            '( --minimum-release-age)--minimum-release-age[Only install packages published at least N seconds ago (security feature)]' \
            '( --cpu)--cpu[Override CPU architecture for optional dependencies (e.g., x64, arm64, * for all)]' \
            '( --os)--os[Override operating system for optional dependencies (e.g., linux, darwin, * for all)]' \
            '( -h --help) -h--help[Print this help menu]' \
            '( -d --dev) -d--dev[Add dependency to "devDependencies"]' \
            '( --optional)--optional[Add dependency to "optionalDependencies"]' \
            '( --peer)--peer[Add dependency to "peerDependencies"]' \
            '( -E --exact) -E--exact[Add the exact version instead of the ^range]' \
            '( -a --analyze) -a--analyze[Recursively analyze & install dependencies of files passed as arguments (using Bun'\''s bundler)]' \
            '( --only-missing)--only-missing[Only add dependencies to package.json if they are not already present]'
          ;;
        remove|rm)
          _arguments -s -S \
            '( -c --config) -c--config[Specify path to config file (bunfig.toml)]' \
            '( -y --yarn) -y--yarn[Write a yarn.lock file (yarn v1)]' \
            '( -p --production) -p--production[Don'\''t install devDependencies]' \
            '( --no-save)--no-save[Don'\''t update package.json or save a lockfile]' \
            '( --save)--save[Save to package.json (true by default)]' \
            '( --ca)--ca[Provide a Certificate Authority signing certificate]' \
            '( --cafile)--cafile[The same as `--ca`, but is a file path to the certificate]' \
            '( --dry-run)--dry-run[Perform a dry run without making changes]' \
            '( --frozen-lockfile)--frozen-lockfile[Disallow changes to lockfile]' \
            '( -f --force) -f--force[Always request the latest versions from the registry & reinstall all dependencies]' \
            '( --cache-dir)--cache-dir[Store & load cached data from a specific directory path]' \
            '( --no-cache)--no-cache[Ignore manifest cache entirely]' \
            '( --silent)--silent[Don'\''t log anything]' \
            '( --quiet)--quiet[Only show tarball name when packing]' \
            '( --verbose)--verbose[Excessively verbose logging]' \
            '( --no-progress)--no-progress[Disable the progress bar]' \
            '( --no-summary)--no-summary[Don'\''t print a summary]' \
            '( --no-verify)--no-verify[Skip verifying integrity of newly downloaded packages]' \
            '( --ignore-scripts)--ignore-scripts[Skip lifecycle scripts in the project'\''s package.json (dependency scripts are never run)]' \
            '( --trust)--trust[Add to trustedDependencies in the project'\''s package.json and install the package(s)]' \
            '( -g --global) -g--global[Install globally]' \
            '( --cwd)--cwd[Set a specific cwd]' \
            '( --backend)--backend[Platform-specific optimizations for installing dependencies. Possible values: "clonefile" (default), "hardlink", "symlink", "copyfile"]' \
            '( --registry)--registry[Use a specific registry by default, overriding .npmrc, bunfig.toml and environment variables]' \
            '( --concurrent-scripts)--concurrent-scripts[Maximum number of concurrent jobs for lifecycle scripts (default: 2x CPU cores)]' \
            '( --network-concurrency)--network-concurrency[Maximum number of concurrent network requests (default 48)]' \
            '( --save-text-lockfile)--save-text-lockfile[Save a text-based lockfile]' \
            '( --omit)--omit[Exclude '\''dev'\'', '\''optional'\'', or '\''peer'\'' dependencies from install]' \
            '( --lockfile-only)--lockfile-only[Generate a lockfile without installing dependencies]' \
            '( --linker)--linker[Linker strategy (one of "isolated" or "hoisted")]' \
            '( --minimum-release-age)--minimum-release-age[Only install packages published at least N seconds ago (security feature)]' \
            '( --cpu)--cpu[Override CPU architecture for optional dependencies (e.g., x64, arm64, * for all)]' \
            '( --os)--os[Override operating system for optional dependencies (e.g., linux, darwin, * for all)]' \
            '( -h --help) -h--help[Print this help menu]'
          _bun_installed_packages
          ;;
        update)
          _arguments -s -S \
            '( -c --config) -c--config[Specify path to config file (bunfig.toml)]' \
            '( -y --yarn) -y--yarn[Write a yarn.lock file (yarn v1)]' \
            '( -p --production) -p--production[Don'\''t install devDependencies]' \
            '( --no-save)--no-save[Don'\''t update package.json or save a lockfile]' \
            '( --save)--save[Save to package.json (true by default)]' \
            '( --ca)--ca[Provide a Certificate Authority signing certificate]' \
            '( --cafile)--cafile[The same as `--ca`, but is a file path to the certificate]' \
            '( --dry-run)--dry-run[Perform a dry run without making changes]' \
            '( --frozen-lockfile)--frozen-lockfile[Disallow changes to lockfile]' \
            '( -f --force) -f--force[Always request the latest versions from the registry & reinstall all dependencies]' \
            '( --cache-dir)--cache-dir[Store & load cached data from a specific directory path]' \
            '( --no-cache)--no-cache[Ignore manifest cache entirely]' \
            '( --silent)--silent[Don'\''t log anything]' \
            '( --quiet)--quiet[Only show tarball name when packing]' \
            '( --verbose)--verbose[Excessively verbose logging]' \
            '( --no-progress)--no-progress[Disable the progress bar]' \
            '( --no-summary)--no-summary[Don'\''t print a summary]' \
            '( --no-verify)--no-verify[Skip verifying integrity of newly downloaded packages]' \
            '( --ignore-scripts)--ignore-scripts[Skip lifecycle scripts in the project'\''s package.json (dependency scripts are never run)]' \
            '( --trust)--trust[Add to trustedDependencies in the project'\''s package.json and install the package(s)]' \
            '( -g --global) -g--global[Install globally]' \
            '( --cwd)--cwd[Set a specific cwd]' \
            '( --backend)--backend[Platform-specific optimizations for installing dependencies. Possible values: "clonefile" (default), "hardlink", "symlink", "copyfile"]' \
            '( --registry)--registry[Use a specific registry by default, overriding .npmrc, bunfig.toml and environment variables]' \
            '( --concurrent-scripts)--concurrent-scripts[Maximum number of concurrent jobs for lifecycle scripts (default: 2x CPU cores)]' \
            '( --network-concurrency)--network-concurrency[Maximum number of concurrent network requests (default 48)]' \
            '( --save-text-lockfile)--save-text-lockfile[Save a text-based lockfile]' \
            '( --omit)--omit[Exclude '\''dev'\'', '\''optional'\'', or '\''peer'\'' dependencies from install]' \
            '( --lockfile-only)--lockfile-only[Generate a lockfile without installing dependencies]' \
            '( --linker)--linker[Linker strategy (one of "isolated" or "hoisted")]' \
            '( --minimum-release-age)--minimum-release-age[Only install packages published at least N seconds ago (security feature)]' \
            '( --cpu)--cpu[Override CPU architecture for optional dependencies (e.g., x64, arm64, * for all)]' \
            '( --os)--os[Override operating system for optional dependencies (e.g., linux, darwin, * for all)]' \
            '( -h --help) -h--help[Print this help menu]' \
            '( --latest)--latest[Update packages to their latest versions]' \
            '( -i --interactive) -i--interactive[Show an interactive list of outdated packages to select for update]' \
            '( --filter)--filter[Update packages for the matching workspaces]' \
            '( -r --recursive) -r--recursive[Update packages in all workspaces]'
          ;;
        audit)
          _arguments -s -S \
            '( --json)--json[Output in JSON format]' \
            '( --audit-level)--audit-level[Only print advisories with severity greater than or equal to  (low, moderate, high, critical)]' \
            '( --ignore)--ignore[Ignore specific CVE IDs from audit]'
          ;;
        outdated)
          _arguments -s -S \
            '( -c --config) -c--config[Specify path to config file (bunfig.toml)]' \
            '( -y --yarn) -y--yarn[Write a yarn.lock file (yarn v1)]' \
            '( -p --production) -p--production[Don'\''t install devDependencies]' \
            '( --no-save)--no-save[Don'\''t update package.json or save a lockfile]' \
            '( --save)--save[Save to package.json (true by default)]' \
            '( --ca)--ca[Provide a Certificate Authority signing certificate]' \
            '( --cafile)--cafile[The same as `--ca`, but is a file path to the certificate]' \
            '( --dry-run)--dry-run[Perform a dry run without making changes]' \
            '( --frozen-lockfile)--frozen-lockfile[Disallow changes to lockfile]' \
            '( -f --force) -f--force[Always request the latest versions from the registry & reinstall all dependencies]' \
            '( --cache-dir)--cache-dir[Store & load cached data from a specific directory path]' \
            '( --no-cache)--no-cache[Ignore manifest cache entirely]' \
            '( --silent)--silent[Don'\''t log anything]' \
            '( --quiet)--quiet[Only show tarball name when packing]' \
            '( --verbose)--verbose[Excessively verbose logging]' \
            '( --no-progress)--no-progress[Disable the progress bar]' \
            '( --no-summary)--no-summary[Don'\''t print a summary]' \
            '( --no-verify)--no-verify[Skip verifying integrity of newly downloaded packages]' \
            '( --ignore-scripts)--ignore-scripts[Skip lifecycle scripts in the project'\''s package.json (dependency scripts are never run)]' \
            '( --trust)--trust[Add to trustedDependencies in the project'\''s package.json and install the package(s)]' \
            '( -g --global) -g--global[Install globally]' \
            '( --cwd)--cwd[Set a specific cwd]' \
            '( --backend)--backend[Platform-specific optimizations for installing dependencies. Possible values: "clonefile" (default), "hardlink", "symlink", "copyfile"]' \
            '( --registry)--registry[Use a specific registry by default, overriding .npmrc, bunfig.toml and environment variables]' \
            '( --concurrent-scripts)--concurrent-scripts[Maximum number of concurrent jobs for lifecycle scripts (default: 2x CPU cores)]' \
            '( --network-concurrency)--network-concurrency[Maximum number of concurrent network requests (default 48)]' \
            '( --save-text-lockfile)--save-text-lockfile[Save a text-based lockfile]' \
            '( --omit)--omit[Exclude '\''dev'\'', '\''optional'\'', or '\''peer'\'' dependencies from install]' \
            '( --lockfile-only)--lockfile-only[Generate a lockfile without installing dependencies]' \
            '( --linker)--linker[Linker strategy (one of "isolated" or "hoisted")]' \
            '( --minimum-release-age)--minimum-release-age[Only install packages published at least N seconds ago (security feature)]' \
            '( --cpu)--cpu[Override CPU architecture for optional dependencies (e.g., x64, arm64, * for all)]' \
            '( --os)--os[Override operating system for optional dependencies (e.g., linux, darwin, * for all)]' \
            '( -h --help) -h--help[Print this help menu]' \
            '( -F --filter) -F--filter[Display outdated dependencies for each matching workspace]' \
            '( -r --recursive) -r--recursive[Check outdated packages in all workspaces]'
          ;;
        link)
          _arguments -s -S \
            '( -c --config) -c--config[Specify path to config file (bunfig.toml)]' \
            '( -y --yarn) -y--yarn[Write a yarn.lock file (yarn v1)]' \
            '( -p --production) -p--production[Don'\''t install devDependencies]' \
            '( --no-save)--no-save[Don'\''t update package.json or save a lockfile]' \
            '( --save)--save[Save to package.json (true by default)]' \
            '( --ca)--ca[Provide a Certificate Authority signing certificate]' \
            '( --cafile)--cafile[The same as `--ca`, but is a file path to the certificate]' \
            '( --dry-run)--dry-run[Perform a dry run without making changes]' \
            '( --frozen-lockfile)--frozen-lockfile[Disallow changes to lockfile]' \
            '( -f --force) -f--force[Always request the latest versions from the registry & reinstall all dependencies]' \
            '( --cache-dir)--cache-dir[Store & load cached data from a specific directory path]' \
            '( --no-cache)--no-cache[Ignore manifest cache entirely]' \
            '( --silent)--silent[Don'\''t log anything]' \
            '( --quiet)--quiet[Only show tarball name when packing]' \
            '( --verbose)--verbose[Excessively verbose logging]' \
            '( --no-progress)--no-progress[Disable the progress bar]' \
            '( --no-summary)--no-summary[Don'\''t print a summary]' \
            '( --no-verify)--no-verify[Skip verifying integrity of newly downloaded packages]' \
            '( --ignore-scripts)--ignore-scripts[Skip lifecycle scripts in the project'\''s package.json (dependency scripts are never run)]' \
            '( --trust)--trust[Add to trustedDependencies in the project'\''s package.json and install the package(s)]' \
            '( -g --global) -g--global[Install globally]' \
            '( --cwd)--cwd[Set a specific cwd]' \
            '( --backend)--backend[Platform-specific optimizations for installing dependencies. Possible values: "clonefile" (default), "hardlink", "symlink", "copyfile"]' \
            '( --registry)--registry[Use a specific registry by default, overriding .npmrc, bunfig.toml and environment variables]' \
            '( --concurrent-scripts)--concurrent-scripts[Maximum number of concurrent jobs for lifecycle scripts (default: 2x CPU cores)]' \
            '( --network-concurrency)--network-concurrency[Maximum number of concurrent network requests (default 48)]' \
            '( --save-text-lockfile)--save-text-lockfile[Save a text-based lockfile]' \
            '( --omit)--omit[Exclude '\''dev'\'', '\''optional'\'', or '\''peer'\'' dependencies from install]' \
            '( --lockfile-only)--lockfile-only[Generate a lockfile without installing dependencies]' \
            '( --linker)--linker[Linker strategy (one of "isolated" or "hoisted")]' \
            '( --minimum-release-age)--minimum-release-age[Only install packages published at least N seconds ago (security feature)]' \
            '( --cpu)--cpu[Override CPU architecture for optional dependencies (e.g., x64, arm64, * for all)]' \
            '( --os)--os[Override operating system for optional dependencies (e.g., linux, darwin, * for all)]' \
            '( -h --help) -h--help[Print this help menu]'
          ;;
        unlink)
          _arguments -s -S \
            '( -c --config) -c--config[Specify path to config file (bunfig.toml)]' \
            '( -y --yarn) -y--yarn[Write a yarn.lock file (yarn v1)]' \
            '( -p --production) -p--production[Don'\''t install devDependencies]' \
            '( --no-save)--no-save[Don'\''t update package.json or save a lockfile]' \
            '( --save)--save[Save to package.json (true by default)]' \
            '( --ca)--ca[Provide a Certificate Authority signing certificate]' \
            '( --cafile)--cafile[The same as `--ca`, but is a file path to the certificate]' \
            '( --dry-run)--dry-run[Perform a dry run without making changes]' \
            '( --frozen-lockfile)--frozen-lockfile[Disallow changes to lockfile]' \
            '( -f --force) -f--force[Always request the latest versions from the registry & reinstall all dependencies]' \
            '( --cache-dir)--cache-dir[Store & load cached data from a specific directory path]' \
            '( --no-cache)--no-cache[Ignore manifest cache entirely]' \
            '( --silent)--silent[Don'\''t log anything]' \
            '( --quiet)--quiet[Only show tarball name when packing]' \
            '( --verbose)--verbose[Excessively verbose logging]' \
            '( --no-progress)--no-progress[Disable the progress bar]' \
            '( --no-summary)--no-summary[Don'\''t print a summary]' \
            '( --no-verify)--no-verify[Skip verifying integrity of newly downloaded packages]' \
            '( --ignore-scripts)--ignore-scripts[Skip lifecycle scripts in the project'\''s package.json (dependency scripts are never run)]' \
            '( --trust)--trust[Add to trustedDependencies in the project'\''s package.json and install the package(s)]' \
            '( -g --global) -g--global[Install globally]' \
            '( --cwd)--cwd[Set a specific cwd]' \
            '( --backend)--backend[Platform-specific optimizations for installing dependencies. Possible values: "clonefile" (default), "hardlink", "symlink", "copyfile"]' \
            '( --registry)--registry[Use a specific registry by default, overriding .npmrc, bunfig.toml and environment variables]' \
            '( --concurrent-scripts)--concurrent-scripts[Maximum number of concurrent jobs for lifecycle scripts (default: 2x CPU cores)]' \
            '( --network-concurrency)--network-concurrency[Maximum number of concurrent network requests (default 48)]' \
            '( --save-text-lockfile)--save-text-lockfile[Save a text-based lockfile]' \
            '( --omit)--omit[Exclude '\''dev'\'', '\''optional'\'', or '\''peer'\'' dependencies from install]' \
            '( --lockfile-only)--lockfile-only[Generate a lockfile without installing dependencies]' \
            '( --linker)--linker[Linker strategy (one of "isolated" or "hoisted")]' \
            '( --minimum-release-age)--minimum-release-age[Only install packages published at least N seconds ago (security feature)]' \
            '( --cpu)--cpu[Override CPU architecture for optional dependencies (e.g., x64, arm64, * for all)]' \
            '( --os)--os[Override operating system for optional dependencies (e.g., linux, darwin, * for all)]' \
            '( -h --help) -h--help[Print this help menu]'
          ;;
        publish)
          _arguments -s -S \
            '( -c --config) -c--config[Specify path to config file (bunfig.toml)]' \
            '( -y --yarn) -y--yarn[Write a yarn.lock file (yarn v1)]' \
            '( -p --production) -p--production[Don'\''t install devDependencies]' \
            '( --no-save)--no-save[Don'\''t update package.json or save a lockfile]' \
            '( --save)--save[Save to package.json (true by default)]' \
            '( --ca)--ca[Provide a Certificate Authority signing certificate]' \
            '( --cafile)--cafile[The same as `--ca`, but is a file path to the certificate]' \
            '( --dry-run)--dry-run[Perform a dry run without making changes]' \
            '( --frozen-lockfile)--frozen-lockfile[Disallow changes to lockfile]' \
            '( -f --force) -f--force[Always request the latest versions from the registry & reinstall all dependencies]' \
            '( --cache-dir)--cache-dir[Store & load cached data from a specific directory path]' \
            '( --no-cache)--no-cache[Ignore manifest cache entirely]' \
            '( --silent)--silent[Don'\''t log anything]' \
            '( --quiet)--quiet[Only show tarball name when packing]' \
            '( --verbose)--verbose[Excessively verbose logging]' \
            '( --no-progress)--no-progress[Disable the progress bar]' \
            '( --no-summary)--no-summary[Don'\''t print a summary]' \
            '( --no-verify)--no-verify[Skip verifying integrity of newly downloaded packages]' \
            '( --ignore-scripts)--ignore-scripts[Skip lifecycle scripts in the project'\''s package.json (dependency scripts are never run)]' \
            '( --trust)--trust[Add to trustedDependencies in the project'\''s package.json and install the package(s)]' \
            '( -g --global) -g--global[Install globally]' \
            '( --cwd)--cwd[Set a specific cwd]' \
            '( --backend)--backend[Platform-specific optimizations for installing dependencies. Possible values: "clonefile" (default), "hardlink", "symlink", "copyfile"]' \
            '( --registry)--registry[Use a specific registry by default, overriding .npmrc, bunfig.toml and environment variables]' \
            '( --concurrent-scripts)--concurrent-scripts[Maximum number of concurrent jobs for lifecycle scripts (default: 2x CPU cores)]' \
            '( --network-concurrency)--network-concurrency[Maximum number of concurrent network requests (default 48)]' \
            '( --save-text-lockfile)--save-text-lockfile[Save a text-based lockfile]' \
            '( --omit)--omit[Exclude '\''dev'\'', '\''optional'\'', or '\''peer'\'' dependencies from install]' \
            '( --lockfile-only)--lockfile-only[Generate a lockfile without installing dependencies]' \
            '( --linker)--linker[Linker strategy (one of "isolated" or "hoisted")]' \
            '( --minimum-release-age)--minimum-release-age[Only install packages published at least N seconds ago (security feature)]' \
            '( --cpu)--cpu[Override CPU architecture for optional dependencies (e.g., x64, arm64, * for all)]' \
            '( --os)--os[Override operating system for optional dependencies (e.g., linux, darwin, * for all)]' \
            '( -h --help) -h--help[Print this help menu]' \
            '( --access)--access[Set access level for scoped packages]' \
            '( --tag)--tag[Tag the release. Default is "latest"]' \
            '( --otp)--otp[Provide a one-time password for authentication]' \
            '( --auth-type)--auth-type[Specify the type of one-time password authentication (default is '\''web'\'')]' \
            '( --gzip-level)--gzip-level[Specify a custom compression level for gzip. Default is 9.]' \
            '( --tolerate-republish)--tolerate-republish[Don'\''t exit with code 1 when republishing over an existing version number]'
          ;;
        patch)
          _arguments -s -S \
            '( -c --config) -c--config[Specify path to config file (bunfig.toml)]' \
            '( -y --yarn) -y--yarn[Write a yarn.lock file (yarn v1)]' \
            '( -p --production) -p--production[Don'\''t install devDependencies]' \
            '( --no-save)--no-save[Don'\''t update package.json or save a lockfile]' \
            '( --save)--save[Save to package.json (true by default)]' \
            '( --ca)--ca[Provide a Certificate Authority signing certificate]' \
            '( --cafile)--cafile[The same as `--ca`, but is a file path to the certificate]' \
            '( --dry-run)--dry-run[Perform a dry run without making changes]' \
            '( --frozen-lockfile)--frozen-lockfile[Disallow changes to lockfile]' \
            '( -f --force) -f--force[Always request the latest versions from the registry & reinstall all dependencies]' \
            '( --cache-dir)--cache-dir[Store & load cached data from a specific directory path]' \
            '( --no-cache)--no-cache[Ignore manifest cache entirely]' \
            '( --silent)--silent[Don'\''t log anything]' \
            '( --quiet)--quiet[Only show tarball name when packing]' \
            '( --verbose)--verbose[Excessively verbose logging]' \
            '( --no-progress)--no-progress[Disable the progress bar]' \
            '( --no-summary)--no-summary[Don'\''t print a summary]' \
            '( --no-verify)--no-verify[Skip verifying integrity of newly downloaded packages]' \
            '( --ignore-scripts)--ignore-scripts[Skip lifecycle scripts in the project'\''s package.json (dependency scripts are never run)]' \
            '( --trust)--trust[Add to trustedDependencies in the project'\''s package.json and install the package(s)]' \
            '( -g --global) -g--global[Install globally]' \
            '( --cwd)--cwd[Set a specific cwd]' \
            '( --backend)--backend[Platform-specific optimizations for installing dependencies. Possible values: "clonefile" (default), "hardlink", "symlink", "copyfile"]' \
            '( --registry)--registry[Use a specific registry by default, overriding .npmrc, bunfig.toml and environment variables]' \
            '( --concurrent-scripts)--concurrent-scripts[Maximum number of concurrent jobs for lifecycle scripts (default: 2x CPU cores)]' \
            '( --network-concurrency)--network-concurrency[Maximum number of concurrent network requests (default 48)]' \
            '( --save-text-lockfile)--save-text-lockfile[Save a text-based lockfile]' \
            '( --omit)--omit[Exclude '\''dev'\'', '\''optional'\'', or '\''peer'\'' dependencies from install]' \
            '( --lockfile-only)--lockfile-only[Generate a lockfile without installing dependencies]' \
            '( --linker)--linker[Linker strategy (one of "isolated" or "hoisted")]' \
            '( --minimum-release-age)--minimum-release-age[Only install packages published at least N seconds ago (security feature)]' \
            '( --cpu)--cpu[Override CPU architecture for optional dependencies (e.g., x64, arm64, * for all)]' \
            '( --os)--os[Override operating system for optional dependencies (e.g., linux, darwin, * for all)]' \
            '( -h --help) -h--help[Print this help menu]' \
            '( --commit)--commit[Install a package containing modifications in `dir`]' \
            '( --patches-dir)--patches-dir[The directory to put the patch file in (only if --commit is used)]'
          ;;
        pm)
          _arguments -s -S \
            # no flags
          ;;
        info)
          _arguments -s -S \
            '( -c --config) -c--config[Specify path to config file (bunfig.toml)]' \
            '( -y --yarn) -y--yarn[Write a yarn.lock file (yarn v1)]' \
            '( -p --production) -p--production[Don'\''t install devDependencies]' \
            '( --no-save)--no-save[Don'\''t update package.json or save a lockfile]' \
            '( --save)--save[Save to package.json (true by default)]' \
            '( --ca)--ca[Provide a Certificate Authority signing certificate]' \
            '( --cafile)--cafile[The same as `--ca`, but is a file path to the certificate]' \
            '( --dry-run)--dry-run[Perform a dry run without making changes]' \
            '( --frozen-lockfile)--frozen-lockfile[Disallow changes to lockfile]' \
            '( -f --force) -f--force[Always request the latest versions from the registry & reinstall all dependencies]' \
            '( --cache-dir)--cache-dir[Store & load cached data from a specific directory path]' \
            '( --no-cache)--no-cache[Ignore manifest cache entirely]' \
            '( --silent)--silent[Don'\''t log anything]' \
            '( --quiet)--quiet[Only show tarball name when packing]' \
            '( --verbose)--verbose[Excessively verbose logging]' \
            '( --no-progress)--no-progress[Disable the progress bar]' \
            '( --no-summary)--no-summary[Don'\''t print a summary]' \
            '( --no-verify)--no-verify[Skip verifying integrity of newly downloaded packages]' \
            '( --ignore-scripts)--ignore-scripts[Skip lifecycle scripts in the project'\''s package.json (dependency scripts are never run)]' \
            '( --trust)--trust[Add to trustedDependencies in the project'\''s package.json and install the package(s)]' \
            '( -g --global) -g--global[Install globally]' \
            '( --cwd)--cwd[Set a specific cwd]' \
            '( --backend)--backend[Platform-specific optimizations for installing dependencies. Possible values: "clonefile" (default), "hardlink", "symlink", "copyfile"]' \
            '( --registry)--registry[Use a specific registry by default, overriding .npmrc, bunfig.toml and environment variables]' \
            '( --concurrent-scripts)--concurrent-scripts[Maximum number of concurrent jobs for lifecycle scripts (default: 2x CPU cores)]' \
            '( --network-concurrency)--network-concurrency[Maximum number of concurrent network requests (default 48)]' \
            '( --save-text-lockfile)--save-text-lockfile[Save a text-based lockfile]' \
            '( --omit)--omit[Exclude '\''dev'\'', '\''optional'\'', or '\''peer'\'' dependencies from install]' \
            '( --lockfile-only)--lockfile-only[Generate a lockfile without installing dependencies]' \
            '( --linker)--linker[Linker strategy (one of "isolated" or "hoisted")]' \
            '( --minimum-release-age)--minimum-release-age[Only install packages published at least N seconds ago (security feature)]' \
            '( --cpu)--cpu[Override CPU architecture for optional dependencies (e.g., x64, arm64, * for all)]' \
            '( --os)--os[Override operating system for optional dependencies (e.g., linux, darwin, * for all)]' \
            '( -h --help) -h--help[Print this help menu]' \
            '( --json)--json[Output in JSON format]'
          ;;
        why)
          _arguments -s -S \
            # no flags
          ;;
        build)
          _arguments -s -S \
            '( --production)--production[Set NODE_ENV=production and enable minification]' \
            '( --compile)--compile[Generate a standalone Bun executable containing your bundled code. Implies --production]' \
            '( --compile-exec-argv)--compile-exec-argv[Prepend arguments to the standalone executable'\''s execArgv]' \
            '( --compile-autoload-dotenv)--compile-autoload-dotenv[Enable autoloading of .env files in standalone executable (default: true)]' \
            '( --no-compile-autoload-dotenv)--no-compile-autoload-dotenv[Disable autoloading of .env files in standalone executable]' \
            '( --compile-autoload-bunfig)--compile-autoload-bunfig[Enable autoloading of bunfig.toml in standalone executable (default: true)]' \
            '( --no-compile-autoload-bunfig)--no-compile-autoload-bunfig[Disable autoloading of bunfig.toml in standalone executable]' \
            '( --compile-autoload-tsconfig)--compile-autoload-tsconfig[Enable autoloading of tsconfig.json at runtime in standalone executable (default: false)]' \
            '( --no-compile-autoload-tsconfig)--no-compile-autoload-tsconfig[Disable autoloading of tsconfig.json at runtime in standalone executable]' \
            '( --compile-autoload-package-json)--compile-autoload-package-json[Enable autoloading of package.json at runtime in standalone executable (default: false)]' \
            '( --no-compile-autoload-package-json)--no-compile-autoload-package-json[Disable autoloading of package.json at runtime in standalone executable]' \
            '( --compile-executable-path)--compile-executable-path[Path to a Bun executable to use for cross-compilation instead of downloading]' \
            '( --bytecode)--bytecode[Use a bytecode cache]' \
            '( --watch)--watch[Automatically restart the process on file change]' \
            '( --no-clear-screen)--no-clear-screen[Disable clearing the terminal screen on reload when --watch is enabled]' \
            '( --target)--target[The intended execution environment for the bundle. "browser", "bun" or "node"]' \
            '( --outdir)--outdir[Default to "dist" if multiple files]' \
            '( --outfile)--outfile[Write to a file]' \
            '( --metafile)--metafile[Write a JSON file with metadata about the build]' \
            '( --metafile-md)--metafile-md[Write a markdown file with a visualization of the module graph (LLM-friendly)]' \
            '( --sourcemap)--sourcemap[Build with sourcemaps - '\''linked'\'', '\''inline'\'', '\''external'\'', or '\''none'\'']' \
            '( --banner)--banner[Add a banner to the bundled output such as "use client"; for a bundle being used with RSCs]' \
            '( --footer)--footer[Add a footer to the bundled output such as // built with bun!]' \
            '( --format)--format[Specifies the module format to build to. "esm", "cjs" and "iife" are supported. Defaults to "esm", or "cjs" with --bytecode.]' \
            '( --root)--root[Root directory used for multiple entry points]' \
            '( --splitting)--splitting[Enable code splitting]' \
            '( --public-path)--public-path[A prefix to be appended to any import paths in bundled code]' \
            '( -e --external) -e--external[Exclude module from transpilation (can use * wildcards). ex: -e react]' \
            '( --allow-unresolved)--allow-unresolved[Allow unresolved dynamic import()/require() specifiers matching these glob patterns. Use '\'''\'' for opaque specifiers. Default is '\''*'\'' (allow all).]' \
            '( --reject-unresolved)--reject-unresolved[Fail the build on any dynamic import()/require() specifier that cannot be resolved at build time.]' \
            '( --packages)--packages[Add dependencies to bundle or keep them external. "external", "bundle" is supported. Defaults to "bundle".]' \
            '( --entry-naming)--entry-naming[Customize entry point filenames. Defaults to "[dir]/[name].[ext]"]' \
            '( --chunk-naming)--chunk-naming[Customize chunk filenames. Defaults to "[name]-[hash].[ext]"]' \
            '( --asset-naming)--asset-naming[Customize asset filenames. Defaults to "[name]-[hash].[ext]"]' \
            '( --react-fast-refresh)--react-fast-refresh[Enable React Fast Refresh transform (does not emit hot-module code, use this for testing)]' \
            '( --react-compiler)--react-compiler[Enable the React Compiler optimizing transform]' \
            '( --no-bundle)--no-bundle[Transpile file only, do not bundle]' \
            '( --emit-dce-annotations)--emit-dce-annotations[Re-emit DCE annotations in bundles. Enabled by default unless --minify-whitespace is passed.]' \
            '( --minify)--minify[Enable all minification flags]' \
            '( --minify-syntax)--minify-syntax[Minify syntax and inline data]' \
            '( --minify-whitespace)--minify-whitespace[Minify whitespace]' \
            '( --minify-identifiers)--minify-identifiers[Minify identifiers]' \
            '( --keep-names)--keep-names[Preserve original function and class names when minifying]' \
            '( --css-chunking)--css-chunking[Chunk CSS files together to reduce duplicated CSS loaded in a browser. Only has an effect when multiple entrypoints import CSS]' \
            '( --conditions)--conditions[Pass custom conditions to resolve]' \
            '( --app)--app[(EXPERIMENTAL) Build a web app for production using Bun Bake.]' \
            '( --server-components)--server-components[(EXPERIMENTAL) Enable server components]' \
            '( --env)--env[Inline environment variables into the bundle as process.env.${name}. Defaults to '\''disable'\''. To inline environment variables matching a prefix, use my prefix like '\''FOO_PUBLIC_*'\''.]' \
            '( --windows-hide-console)--windows-hide-console[When using --compile targeting Windows, prevent a Command prompt from opening alongside the executable]' \
            '( --windows-icon)--windows-icon[When using --compile targeting Windows, assign an executable icon]' \
            '( --windows-title)--windows-title[When using --compile targeting Windows, set the executable product name]' \
            '( --windows-publisher)--windows-publisher[When using --compile targeting Windows, set the executable company name]' \
            '( --windows-version)--windows-version[When using --compile targeting Windows, set the executable version (e.g. 1.2.3.4)]' \
            '( --windows-description)--windows-description[When using --compile targeting Windows, set the executable description]' \
            '( --windows-copyright)--windows-copyright[When using --compile targeting Windows, set the executable copyright]' \
            '( --debug-dump-server-files)--debug-dump-server-files[When --app is set, dump all server files to disk even when building statically]' \
            '( --debug-no-minify)--debug-no-minify[When --app is set, do not minify anything]'
          _bun_files
          ;;
        init)
          _arguments -s -S \
            '( --help)--help[Print this menu]' \
            '( -y --yes) -y--yes[Accept all default options]' \
            '( -m --minimal) -m--minimal[Only initialize type definitions]' \
            '( -r --react) -r--react[Initialize a React project]' \
            '( --react)--react[tailwind]' \
            '( --react)--react[shadcn]'
          ;;
        create|c)
          _arguments -s -S \
            # no flags
          ;;
        upgrade)
          _arguments -s -S \
            # no flags
          ;;
        feedback)
          _arguments -s -S \
            # no flags
          ;;
      esac
      ;;
  esac
}

_bun "$@"
